export interface BirdPreset {
  id: string;
  name: string;
  dutchName?: string;
  category: string;
  emoji: string;
  description: string;
  waveType: "sine" | "triangle" | "sawtooth" | "square";
  baseFreq: number;
  freqChange: number;
  sweepType: "up" | "down" | "vibrato" | "trill" | "double" | "warble" | "bell" | "triplet" | "clicks" | "gurgle" | "cascade";
  duration: number;
  repeatCount: number;
  interval: number;
  lfoFreq?: number;
}

export const BIRD_CATEGORIES = [
  { id: "lofi", name: "🏆 AI & Lo-Fi Essentials" },
  { id: "songbirds", name: "🎵 Songbirds & Melodic Singers" },
  { id: "mimics", name: "🎭 Mimics & Complex Vocalists" },
  { id: "flute", name: "🎷 Whistling & Flute-Like" },
  { id: "indian", name: "🇮🇳 Indian Birds (Beautiful Songs)" },
  { id: "belgian", name: "🇧🇪 Belgian Ardennes Birds" },
  { id: "taiwan", name: "🇹🇼 Taiwanese Birds" },
  { id: "australian", name: "🇦🇺 Australian Birds" },
  { id: "japan", name: "🇯🇵 Japanese Birds" },
  { id: "china", name: "🇨🇳 Chinese Birds" },
  { id: "brazil", name: "🇧🇷 Brazilian Birds" },
  { id: "africa", name: "🇿🇦 African Birds" },
  { id: "middleeast", name: "🇦🇪 Middle Eastern Birds" },
  { id: "nordic", name: "🇸🇪 Nordic & Arctic Birds" },
  { id: "europe", name: "🇪🇺 European National Birds" },
  { id: "asia", name: "🌏 Asian National Birds" },
  { id: "northamerica", name: "🌎 North & Central American Birds" },
  { id: "southamerica", name: "🌵 South American Birds" },
  { id: "oceania", name: "🦘 Oceania & Pacific Birds" },
  { id: "tropical", name: "🌴 Tropical & Exotic Voices" },
  { id: "notable", name: "🌟 Additional Notable Singers" }
];

export const BIRD_PRESETS: BirdPreset[] = [
  // SECTION 1: AI & Lo-Fi Essentials (Top recommendations for beat crafting)
  {
    id: "malabarwhistlingthrush",
    name: "Malabar Whistling Thrush",
    category: "lofi",
    emoji: "🎶",
    description: "Whistling idle schoolboy tune; blends perfectly with mellow lo-fi chords",
    waveType: "sine",
    baseFreq: 1800,
    freqChange: -400,
    sweepType: "warble",
    duration: 0.65,
    repeatCount: 4,
    interval: 0.75,
    lfoFreq: 6
  },
  {
    id: "shama",
    name: "White-rumped Shama",
    category: "lofi",
    emoji: "🧡",
    description: "Flute-like liquid melodies, rich echoes, outstanding for spatial ambient pads",
    waveType: "sine",
    baseFreq: 2200,
    freqChange: 800,
    sweepType: "vibrato",
    duration: 0.55,
    repeatCount: 3,
    interval: 0.65,
    lfoFreq: 14
  },
  {
    id: "asiankoel",
    name: "Asian Koel",
    category: "lofi",
    emoji: "🖤",
    description: "Rising full-throated 'ko-el... ko-el' call that signals tropical nights",
    waveType: "sine",
    baseFreq: 1100,
    freqChange: 700,
    sweepType: "up",
    duration: 0.45,
    repeatCount: 2,
    interval: 0.8
  },
  {
    id: "nightingale",
    name: "Common Nightingale",
    dutchName: "Nachtegaal",
    category: "lofi",
    emoji: "🌙",
    description: "Famous deep romantic night-time warble with emotional piping tones",
    waveType: "triangle",
    baseFreq: 1950,
    freqChange: 350,
    sweepType: "trill",
    duration: 0.5,
    repeatCount: 4,
    interval: 0.55,
    lfoFreq: 18
  },
  {
    id: "tui",
    name: "Tui",
    category: "lofi",
    emoji: "🇳🇿",
    description: "Exotic bell chimes, mechanical clicks, and deep fluted note drops",
    waveType: "triangle",
    baseFreq: 2500,
    freqChange: -1200,
    sweepType: "bell",
    duration: 0.35,
    repeatCount: 5,
    interval: 0.4,
    lfoFreq: 8
  },
  {
    id: "skylark",
    name: "Common Skylark",
    dutchName: "Veldleeuwerik",
    category: "lofi",
    emoji: "☁️",
    description: "Cascading rapid wall of high-frequency joyous whistles",
    waveType: "sine",
    baseFreq: 3400,
    freqChange: -900,
    sweepType: "cascade",
    duration: 0.4,
    repeatCount: 6,
    interval: 0.45,
    lfoFreq: 22
  },
  {
    id: "woodthrush",
    name: "Wood Thrush",
    dutchName: "Boslijster",
    category: "lofi",
    emoji: "🌲",
    description: "High clear crystalline double-flute sounds resonant across forest floors",
    waveType: "sine",
    baseFreq: 2100,
    freqChange: 500,
    sweepType: "double",
    duration: 0.48,
    repeatCount: 3,
    interval: 0.6
  },
  {
    id: "magpierobin",
    name: "Oriental Magpie-Robin",
    category: "lofi",
    emoji: "🤍",
    description: "Loud, highly-varied whistling scales with rich natural echo response",
    waveType: "sine",
    baseFreq: 2300,
    freqChange: -600,
    sweepType: "triplet",
    duration: 0.38,
    repeatCount: 3,
    interval: 0.5
  },
  {
    id: "canary",
    name: "Warbler Canary",
    category: "lofi",
    emoji: "🟡",
    description: "Fast cheerful golden ripples, classical musical trills & whistles",
    waveType: "triangle",
    baseFreq: 2800,
    freqChange: 400,
    sweepType: "vibrato",
    duration: 0.6,
    repeatCount: 3,
    interval: 0.7,
    lfoFreq: 12
  },
  {
    id: "bulbul",
    name: "Red-whiskered Bulbul",
    category: "lofi",
    emoji: "🍓",
    description: "Happy bouncy bubbly 'pettigrew' whistling sound, highly positive vibe",
    waveType: "sine",
    baseFreq: 1650,
    freqChange: 350,
    sweepType: "gurgle",
    duration: 0.28,
    repeatCount: 4,
    interval: 0.35
  },

  // SECTION 2: Songbirds & Melodic Singers
  {
    id: "robin",
    name: "European Robin",
    dutchName: "Roodborst",
    category: "songbirds",
    emoji: "🐤",
    description: "A series of swift, sweet piping trilled notes rising and falling",
    waveType: "sine",
    baseFreq: 2900,
    freqChange: 600,
    sweepType: "trill",
    duration: 0.3,
    repeatCount: 3,
    interval: 0.4,
    lfoFreq: 15
  },
  {
    id: "blackbird",
    name: "Common Blackbird",
    dutchName: "Merel",
    category: "songbirds",
    emoji: "🐦",
    description: "Deep, rich fluid whistling scales with beautiful melancholy hooks",
    waveType: "sine",
    baseFreq: 1400,
    freqChange: 350,
    sweepType: "warble",
    duration: 0.7,
    repeatCount: 3,
    interval: 0.9,
    lfoFreq: 5
  },
  {
    id: "songthrush",
    name: "Song Thrush",
    dutchName: "Zanglijster",
    category: "songbirds",
    emoji: "🎤",
    description: "Repeats clear brief patterns inside tree tops three to four times",
    waveType: "sine",
    baseFreq: 2500,
    freqChange: -800,
    sweepType: "double",
    duration: 0.35,
    repeatCount: 4,
    interval: 0.45
  },
  {
    id: "hermitthrush",
    name: "Hermit Thrush",
    category: "songbirds",
    emoji: "🍃",
    description: "Pure ethereal fluted pipes cascading downwards at high frequencies",
    waveType: "sine",
    baseFreq: 3100,
    freqChange: -1200,
    sweepType: "cascade",
    duration: 0.5,
    repeatCount: 3,
    interval: 0.65
  },
  {
    id: "housefinch",
    name: "House Finch",
    category: "songbirds",
    emoji: "🏡",
    description: "Bright energetic singing tweets that climb up with a final upward buzz",
    waveType: "sine",
    baseFreq: 2700,
    freqChange: 800,
    sweepType: "up",
    duration: 0.24,
    repeatCount: 5,
    interval: 0.3
  },
  {
    id: "purplefinch",
    name: "Purple Finch",
    category: "songbirds",
    emoji: "💜",
    description: "Lyrical bubbling stream of rapid sweet whistling syllables",
    waveType: "triangle",
    baseFreq: 2600,
    freqChange: 450,
    sweepType: "gurgle",
    duration: 0.32,
    repeatCount: 4,
    interval: 0.4
  },
  {
    id: "goldfinch",
    name: "American Goldfinch",
    category: "songbirds",
    emoji: "🌻",
    description: "Light bouncy cheerful sliding tweets, sounds like 'po-ta-to-chip!'",
    waveType: "sine",
    baseFreq: 3100,
    freqChange: 600,
    sweepType: "triplet",
    duration: 0.2,
    repeatCount: 4,
    interval: 0.32
  },
  {
    id: "yellowhammer",
    name: "Yellowhammer",
    dutchName: "Geelgors",
    category: "songbirds",
    emoji: "🥖",
    description: "Famous rapid monotone notes ending on a long down-slurred whistling sigh",
    waveType: "sine",
    baseFreq: 2400,
    freqChange: -600,
    sweepType: "down",
    duration: 0.8,
    repeatCount: 2,
    interval: 1.0
  },
  {
    id: "indigobunting",
    name: "Indigo Bunting",
    category: "songbirds",
    emoji: "💙",
    description: "High-spirited rapid doublets; notes are always grouped in pairs",
    waveType: "sine",
    baseFreq: 3300,
    freqChange: -700,
    sweepType: "double",
    duration: 0.25,
    repeatCount: 6,
    interval: 0.35
  },
  {
    id: "eastmeadowlark",
    name: "Eastern Meadowlark",
    category: "songbirds",
    emoji: "🌾",
    description: "Slow lazy sliding sweet whistling bells typical of morning grasslands",
    waveType: "sine",
    baseFreq: 2100,
    freqChange: -500,
    sweepType: "bell",
    duration: 0.65,
    repeatCount: 3,
    interval: 0.85
  },
  {
    id: "westmeadowlark",
    name: "Western Meadowlark",
    category: "songbirds",
    emoji: "🤠",
    description: "Rich, bubbly, flute-like gurgled notes cascading down dynamically",
    waveType: "triangle",
    baseFreq: 1750,
    freqChange: -750,
    sweepType: "gurgle",
    duration: 0.55,
    repeatCount: 3,
    interval: 0.72
  },

  // SECTION 3: Mimics & Complex Vocalists
  {
    id: "mockingbird",
    name: "Northern Mockingbird",
    category: "mimics",
    emoji: "🎭",
    description: "Cleverly repeats other bird calls in sequences of threes",
    waveType: "sine",
    baseFreq: 2200,
    freqChange: 300,
    sweepType: "triplet",
    duration: 0.25,
    repeatCount: 6,
    interval: 0.35
  },
  {
    id: "lyrebird",
    name: "Superb Lyrebird",
    category: "mimics",
    emoji: "🪕",
    description: "Amazing metal clicks, chainsaw buzzes, camera clicks & laser bleeps",
    waveType: "sawtooth",
    baseFreq: 4000,
    freqChange: -3500,
    sweepType: "clicks",
    duration: 0.18,
    repeatCount: 8,
    interval: 0.25
  },
  {
    id: "magpie",
    name: "Australian Magpie",
    category: "mimics",
    emoji: "🇦🇺",
    description: "Incredibly deep rich pipe-organ liquid carol whistles",
    waveType: "sine",
    baseFreq: 950,
    freqChange: 650,
    sweepType: "warble",
    duration: 0.7,
    repeatCount: 3,
    interval: 0.8,
    lfoFreq: 4
  },
  {
    id: "starling",
    name: "European Starling",
    dutchName: "Spreeuw",
    category: "mimics",
    emoji: "🔋",
    description: "Cosmic series of whistles, chattering clocks, and high digital beeps",
    waveType: "square",
    baseFreq: 3800,
    freqChange: -2000,
    sweepType: "clicks",
    duration: 0.1,
    repeatCount: 10,
    interval: 0.15
  },
  {
    id: "catbird",
    name: "Gray Catbird",
    category: "mimics",
    emoji: "🐱",
    description: "Nasal cat-like 'meow' call blended with high melodic whistle trills",
    waveType: "triangle",
    baseFreq: 1800,
    freqChange: -400,
    sweepType: "down",
    duration: 0.5,
    repeatCount: 3,
    interval: 0.6
  },

  // SECTION 4: Whistling & Flute-Like Voices
  {
    id: "indiancuckoo",
    name: "Indian Cuckoo",
    category: "flute",
    emoji: "⏱️",
    description: "Four-note rhythmic musical whistle resembling 'one-more-bottle'",
    waveType: "sine",
    baseFreq: 1250,
    freqChange: 150,
    sweepType: "double",
    duration: 0.35,
    repeatCount: 4,
    interval: 0.45
  },
  {
    id: "commoncuckoo",
    name: "Common Cuckoo",
    dutchName: "Koekoek",
    category: "flute",
    emoji: "🕰️",
    description: "Classic pristine double-tone 'coo-coo' scale drop in spring woods",
    waveType: "sine",
    baseFreq: 1050,
    freqChange: -230,
    sweepType: "double",
    duration: 0.4,
    repeatCount: 2,
    interval: 0.7
  },
  {
    id: "whistlingthrush",
    name: "Whistling Thrush",
    category: "flute",
    emoji: "🌬️",
    description: "Extremely loud high flute-like whistles sliding down deeply",
    waveType: "sine",
    baseFreq: 2600,
    freqChange: -1100,
    sweepType: "down",
    duration: 0.75,
    repeatCount: 3,
    interval: 0.9
  },
  {
    id: "goldenoriole",
    name: "Golden Oriole",
    dutchName: "Wielewaal",
    category: "flute",
    emoji: "💛",
    description: "Exquisite warm liquid flute 'weela-wee-ooo' whistle loop",
    waveType: "sine",
    baseFreq: 1150,
    freqChange: 450,
    sweepType: "bell",
    duration: 0.58,
    repeatCount: 3,
    interval: 0.75
  },
  {
    id: "blacknapedoriole",
    name: "Black-naped Oriole",
    category: "flute",
    emoji: "🐥",
    description: "Rich clear whistling bird melody resounding in bamboo groves",
    waveType: "sine",
    baseFreq: 1350,
    freqChange: -300,
    sweepType: "triplet",
    duration: 0.4,
    repeatCount: 3,
    interval: 0.6
  },
  {
    id: "baltimoreoriole",
    name: "Baltimore Oriole",
    category: "flute",
    emoji: "🧡",
    description: "Short series of bright rich piping double notes with spacious pausing",
    waveType: "sine",
    baseFreq: 1900,
    freqChange: 550,
    sweepType: "double",
    duration: 0.5,
    repeatCount: 3,
    interval: 0.7
  },

  // SECTION 5: Indian Birds with Beautiful Songs
  {
    id: "indianrobin",
    name: "Indian Robin",
    category: "indian",
    emoji: "🇮🇳",
    description: "Quick slide-whistles ending on high-precision sweet chirps",
    waveType: "sine",
    baseFreq: 2350,
    freqChange: 650,
    sweepType: "up",
    duration: 0.28,
    repeatCount: 4,
    interval: 0.42
  },
  {
    id: "flycatcher",
    name: "Indian Paradise Flycatcher",
    category: "indian",
    emoji: "🤍",
    description: "Short quick flute whistle with sudden high-pitched whip snaps",
    waveType: "triangle",
    baseFreq: 2400,
    freqChange: 1200,
    sweepType: "clicks",
    duration: 0.15,
    repeatCount: 5,
    interval: 0.25
  },
  {
    id: "redventedbulbul",
    name: "Red-vented Bulbul",
    category: "indian",
    emoji: "🍒",
    description: "Short bubbly gurgled whistles, highly rhythmic and quick",
    waveType: "sine",
    baseFreq: 1550,
    freqChange: 250,
    sweepType: "gurgle",
    duration: 0.25,
    repeatCount: 4,
    interval: 0.32
  },
  {
    id: "junglebabbler",
    name: "Jungle Babbler",
    category: "indian",
    emoji: "🗣️",
    description: "Famous noisy chattering squeaks delivered synchronously in groups of seven",
    waveType: "triangle",
    baseFreq: 1250,
    freqChange: -450,
    sweepType: "clicks",
    duration: 0.12,
    repeatCount: 6,
    interval: 0.18
  },
  {
    id: "commoniora",
    name: "Common Iora",
    category: "indian",
    emoji: "🍋",
    description: "Very long high sustained piping whistle dropping off instantly at the end",
    waveType: "sine",
    baseFreq: 2600,
    freqChange: -1400,
    sweepType: "down",
    duration: 1.1,
    repeatCount: 1,
    interval: 1.5
  },
  {
    id: "indianpitta",
    name: "Indian Pitta",
    category: "indian",
    emoji: "🌈",
    description: "Loud, clear double-whistle 'wheet-tew' rising then dropping rapidly",
    waveType: "sine",
    baseFreq: 1850,
    freqChange: -600,
    sweepType: "double",
    duration: 0.45,
    repeatCount: 2,
    interval: 0.6
  },
  {
    id: "purplesunbird",
    name: "Purple Sunbird",
    category: "indian",
    emoji: "🍇",
    description: "Rapid energetic buzzing metallic click hums that shift frequency",
    waveType: "sawtooth",
    baseFreq: 4500,
    freqChange: -1800,
    sweepType: "vibrato",
    duration: 0.12,
    repeatCount: 8,
    interval: 0.18,
    lfoFreq: 25
  },

  // SECTION 6: Tropical & Exotic Voices
  {
    id: "bellbird",
    name: "New Zealand Bellbird",
    category: "tropical",
    emoji: "🔔",
    description: "Pristine ringing metallic bell chime tones, extremely high fidelity",
    waveType: "sine",
    baseFreq: 3200,
    freqChange: -800,
    sweepType: "bell",
    duration: 0.45,
    repeatCount: 4,
    interval: 0.5
  },
  {
    id: "kokako",
    name: "Kokako",
    category: "tropical",
    emoji: "🌫️",
    description: "Hauntingly slow, deep organ-pipe notes that drift through coastal mist",
    waveType: "sine",
    baseFreq: 850,
    freqChange: 150,
    sweepType: "warble",
    duration: 0.95,
    repeatCount: 2,
    interval: 1.2,
    lfoFreq: 3
  },
  {
    id: "paradistanager",
    name: "Paradise Tanager",
    category: "tropical",
    emoji: "🦜",
    description: "High insect-like rapid electric buzzing sweeps across Amazon canopy",
    waveType: "square",
    baseFreq: 4800,
    freqChange: -1500,
    sweepType: "vibrato",
    duration: 0.22,
    repeatCount: 5,
    interval: 0.28,
    lfoFreq: 30
  },
  {
    id: "scarlettanager",
    name: "Scarlet Tanager",
    category: "tropical",
    emoji: "🎒",
    description: "Raspy, hurried whistling slide; sounds like a robin with a draft cold",
    waveType: "triangle",
    baseFreq: 1850,
    freqChange: 350,
    sweepType: "gurgle",
    duration: 0.4,
    repeatCount: 3,
    interval: 0.55
  },
  {
    id: "cedarwaxwing",
    name: "Cedar Waxwing",
    category: "tropical",
    emoji: "🍒",
    description: "Extremely high thin sibilant lisping whistles that sound like electricity",
    waveType: "sine",
    baseFreq: 6200,
    freqChange: -800,
    sweepType: "trill",
    duration: 0.25,
    repeatCount: 4,
    interval: 0.3,
    lfoFreq: 28
  },
  {
    id: "bohemianwaxwing",
    name: "Bohemian Waxwing",
    category: "tropical",
    emoji: "🍁",
    description: "Ringing high pitch trills similar to small glass bells shaking",
    waveType: "sine",
    baseFreq: 5800,
    freqChange: 300,
    sweepType: "vibrato",
    duration: 0.35,
    repeatCount: 3,
    interval: 0.45,
    lfoFreq: 24
  },
  {
    id: "bluebird",
    name: "Eastern Bluebird",
    category: "tropical",
    emoji: "💙",
    description: "Charming soft warbled slide whistle whistles, rich in peacefulness",
    waveType: "sine",
    baseFreq: 2450,
    freqChange: -450,
    sweepType: "warble",
    duration: 0.48,
    repeatCount: 3,
    interval: 0.65,
    lfoFreq: 5
  },
  {
    id: "rosebreastedgrosbeak",
    name: "Rose-breasted Grosbeak",
    category: "tropical",
    emoji: "🌹",
    description: "Joyful sweet lyrical sliding peaks with deep warmth",
    waveType: "sine",
    baseFreq: 2150,
    freqChange: 750,
    sweepType: "up",
    duration: 0.5,
    repeatCount: 3,
    interval: 0.62
  },
  {
    id: "cardinal",
    name: "Northern Cardinal",
    category: "tropical",
    emoji: "❤️",
    description: "High slurred laser-like 'cheer-cheer-cheer' sweeps that echo widely",
    waveType: "sine",
    baseFreq: 1800,
    freqChange: 1500,
    sweepType: "up",
    duration: 0.45,
    repeatCount: 4,
    interval: 0.6
  },

  // SECTION 7: Additional Notable Singers
  {
    id: "blackheadedgrosbeak",
    name: "Black-headed Grosbeak",
    category: "notable",
    emoji: "🕶️",
    description: "Fast-moving warm gurgling rolling melody; highly complex",
    waveType: "sine",
    baseFreq: 2200,
    freqChange: 400,
    sweepType: "gurgle",
    duration: 0.42,
    repeatCount: 4,
    interval: 0.52
  },
  {
    id: "warblingvireo",
    name: "Warbling Vireo",
    category: "notable",
    emoji: "🎼",
    description: "Very long continuous cheerful wavy phrase that loops elegantly",
    waveType: "sine",
    baseFreq: 2850,
    freqChange: -650,
    sweepType: "warble",
    duration: 0.85,
    repeatCount: 2,
    interval: 1.1,
    lfoFreq: 8
  },
  {
    id: "marshwarbler",
    name: "Marsh Warbler",
    dutchName: "Waterrietzanger",
    category: "notable",
    emoji: "🌾",
    description: "Blisteringly rapid continuous imitations mixed with sweet sliding notes",
    waveType: "triangle",
    baseFreq: 3500,
    freqChange: -1200,
    sweepType: "cascade",
    duration: 0.22,
    repeatCount: 8,
    interval: 0.28,
    lfoFreq: 15
  },
  {
    id: "sedgewarbler",
    name: "Sedge Warbler",
    dutchName: "Rietzanger",
    category: "notable",
    emoji: "🦆",
    description: "Gritty chatter-buzzes blended with sudden bright sliding whistles",
    waveType: "sawtooth",
    baseFreq: 3200,
    freqChange: 1000,
    sweepType: "clicks",
    duration: 0.18,
    repeatCount: 6,
    interval: 0.24
  },
  {
    id: "woodlark",
    name: "Woodlark",
    dutchName: "Boomleeuwerik",
    category: "notable",
    emoji: "🪵",
    description: "Melancholic, beautifully cascading descending'lu-lu-lu' notes",
    waveType: "sine",
    baseFreq: 2100,
    freqChange: -850,
    sweepType: "cascade",
    duration: 0.58,
    repeatCount: 4,
    interval: 0.7
  },
  {
    id: "nightingalethrush",
    name: "Nightingale Thrush",
    category: "notable",
    emoji: "🍂",
    description: "Very delicate fluted warbling notes with quiet woodland space",
    waveType: "sine",
    baseFreq: 2400,
    freqChange: -450,
    sweepType: "triplet",
    duration: 0.4,
    repeatCount: 3,
    interval: 0.65
  },
  {
    id: "robinchat",
    name: "Red-capped Robin-Chat",
    category: "notable",
    emoji: "🧢",
    description: "Exceptional beautiful fluid whistles and perfect mimic sequences",
    waveType: "sine",
    baseFreq: 1950,
    freqChange: 650,
    sweepType: "vibrato",
    duration: 0.52,
    repeatCount: 3,
    interval: 0.68,
    lfoFreq: 12
  },
  {
    id: "laughingthrush",
    name: "Laughingthrush",
    category: "notable",
    emoji: "😆",
    description: "Humorous, loud laughing human-like chatters delivered at high volume",
    waveType: "triangle",
    baseFreq: 1400,
    freqChange: 900,
    sweepType: "gurgle",
    duration: 0.35,
    repeatCount: 4,
    interval: 0.48
  },
  {
    id: "silvereye",
    name: "Silvereye",
    category: "notable",
    emoji: "👓",
    description: "Sweet delicate quiet sliding chirps from low tree hedges",
    waveType: "sine",
    baseFreq: 3700,
    freqChange: -500,
    sweepType: "down",
    duration: 0.18,
    repeatCount: 5,
    interval: 0.25
  },
  {
    id: "bushlark",
    name: "Bush Lark",
    category: "notable",
    emoji: "🌱",
    description: "Brief charming whistles mixed with dry rapid grasswing buzzing",
    waveType: "sawtooth",
    baseFreq: 2900,
    freqChange: -600,
    sweepType: "clicks",
    duration: 0.15,
    repeatCount: 6,
    interval: 0.22
  },
  {
    id: "mourningdove",
    name: "Mourning Dove",
    category: "flute",
    emoji: "🕊️",
    description: "Gentle, soothing coo-OOO-oo-oo calls; creates rich nostalgic morning memories",
    waveType: "sine",
    baseFreq: 900,
    freqChange: 150,
    sweepType: "warble",
    duration: 0.8,
    repeatCount: 3,
    interval: 1.1,
    lfoFreq: 3
  },
  {
    id: "forestowl",
    name: "Forest Owl",
    category: "notable",
    emoji: "🦉",
    description: "Deep hooting pulses echo resonant across remote late-night woodland trails",
    waveType: "triangle",
    baseFreq: 450,
    freqChange: 50,
    sweepType: "bell",
    duration: 0.65,
    repeatCount: 2,
    interval: 0.9,
    lfoFreq: 2
  },
  {
    id: "lilacroller",
    name: "Lilac-breasted Roller",
    category: "tropical",
    emoji: "🌸",
    description: "Energetic vibrant rolling whistles with warm high-harmonic savanna tones",
    waveType: "sawtooth",
    baseFreq: 3100,
    freqChange: -400,
    sweepType: "vibrato",
    duration: 0.35,
    repeatCount: 4,
    interval: 0.5,
    lfoFreq: 18
  },
  {
    id: "woodwarbler",
    name: "Wood Warbler",
    category: "songbirds",
    emoji: "🐤",
    description: "Fascinating high-pitch metallic shivering song that accelerates like a spinning coin",
    waveType: "sine",
    baseFreq: 3300,
    freqChange: -900,
    sweepType: "cascade",
    duration: 0.45,
    repeatCount: 7,
    interval: 0.38,
    lfoFreq: 25
  },
  {
    id: "magpiemelody",
    name: "Australian Magpie Melody",
    category: "lofi",
    emoji: "🖤",
    description: "Flute-like wavy carol chimes with rich ambient depth",
    waveType: "sine",
    baseFreq: 1100,
    freqChange: 550,
    sweepType: "warble",
    duration: 0.6,
    repeatCount: 3,
    interval: 0.8,
    lfoFreq: 6
  },
  {
    id: "nightjar",
    name: "Common Nightjar",
    category: "lofi",
    emoji: "🦉",
    description: "A rapid mechanical woodblock clicking sound; spectacular lofi background texture",
    waveType: "triangle",
    baseFreq: 850,
    freqChange: -150,
    sweepType: "clicks",
    duration: 0.08,
    repeatCount: 16,
    interval: 0.1
  },
  {
    id: "mockingthrush",
    name: "Chuchu Thrush",
    category: "songbirds",
    emoji: "🐦",
    description: "Sudden bright double cascade whistles that repeat with perfect rhythm",
    waveType: "sine",
    baseFreq: 2200,
    freqChange: -800,
    sweepType: "double",
    duration: 0.35,
    repeatCount: 4,
    interval: 0.5
  },
  {
    id: "paintedbunting",
    name: "Painted Bunting",
    category: "songbirds",
    emoji: "🎨",
    description: "A cluster of sweet melodic upward sweeps, extremely rich in harmonics",
    waveType: "sine",
    baseFreq: 3100,
    freqChange: 700,
    sweepType: "up",
    duration: 0.28,
    repeatCount: 5,
    interval: 0.35
  },
  {
    id: "winterwren",
    name: "Winter Wren",
    category: "songbirds",
    emoji: "🪵",
    description: "High-precision rapid cascading trills that shimmer like morning dew",
    waveType: "sine",
    baseFreq: 3800,
    freqChange: -1400,
    sweepType: "vibrato",
    duration: 0.2,
    repeatCount: 8,
    interval: 0.24,
    lfoFreq: 22
  },
  {
    id: "mistlethrush",
    name: "Mistle Thrush",
    dutchName: "Grote Lijster",
    category: "songbirds",
    emoji: "🍂",
    description: "A slow melancholic sliding flute scale; highly peaceful at dusk",
    waveType: "sine",
    baseFreq: 1800,
    freqChange: -300,
    sweepType: "down",
    duration: 0.7,
    repeatCount: 3,
    interval: 0.9
  },
  {
    id: "parakeet",
    name: "Rose-ringed Parakeet",
    category: "mimics",
    emoji: "🦜",
    description: "Vibrant sassy chatter with beautiful high-frequency vibrato elements",
    waveType: "sawtooth",
    baseFreq: 2900,
    freqChange: 400,
    sweepType: "vibrato",
    duration: 0.15,
    repeatCount: 5,
    interval: 0.22,
    lfoFreq: 16
  },
  {
    id: "catbirdblue",
    name: "Blue Gray Catbird",
    category: "mimics",
    emoji: "🐈",
    description: "Playful mimicking slide whistle with a funny nasal tone",
    waveType: "triangle",
    baseFreq: 1600,
    freqChange: -350,
    sweepType: "down",
    duration: 0.45,
    repeatCount: 4,
    interval: 0.55
  },
  {
    id: "spottedbowerbird",
    name: "Spotted Bowerbird",
    category: "mimics",
    emoji: "🏡",
    description: "An incredible range of rapid digital clicking notes and high fluted drops",
    waveType: "square",
    baseFreq: 3400,
    freqChange: -1800,
    sweepType: "clicks",
    duration: 0.12,
    repeatCount: 8,
    interval: 0.18
  },
  {
    id: "hoopoe",
    name: "Eurasian Hoopoe",
    dutchName: "Hop",
    category: "flute",
    emoji: "👑",
    description: "Muffled rhythmic 'oop-oop-oop' double sounds; highly comforting",
    waveType: "sine",
    baseFreq: 680,
    freqChange: 50,
    sweepType: "double",
    duration: 0.35,
    repeatCount: 3,
    interval: 0.65
  },
  {
    id: "taigaflycatcher",
    name: "Taiga Flycatcher",
    category: "flute",
    emoji: "🌲",
    description: "Short double-pulsed high frequency whistle, pristine and clean",
    waveType: "sine",
    baseFreq: 3200,
    freqChange: 300,
    sweepType: "double",
    duration: 0.22,
    repeatCount: 4,
    interval: 0.3
  },
  {
    id: "plaintivecuckoo",
    name: "Plaintive Cuckoo",
    category: "flute",
    emoji: "🌧️",
    description: "Sorrowful high-pitched whistles drooping downwards in rain forests",
    waveType: "sine",
    baseFreq: 2600,
    freqChange: -800,
    sweepType: "down",
    duration: 0.8,
    repeatCount: 3,
    interval: 1.0
  },
  {
    id: "piedcuckoo",
    name: "Pied Crested Cuckoo",
    category: "indian",
    emoji: "🌩️",
    description: "High-frequency rain herald whistles; beautiful double tone",
    waveType: "sine",
    baseFreq: 2400,
    freqChange: 600,
    sweepType: "double",
    duration: 0.4,
    repeatCount: 3,
    interval: 0.58
  },
  {
    id: "tickellsflycatcher",
    name: "Tickell's Blue Flycatcher",
    category: "indian",
    emoji: "💙",
    description: "Very fast metallic warble scales; signs of clean riverbanks",
    waveType: "sine",
    baseFreq: 3300,
    freqChange: -600,
    sweepType: "trill",
    duration: 0.28,
    repeatCount: 5,
    interval: 0.35,
    lfoFreq: 18
  },
  {
    id: "spotteddove",
    name: "Spotted Dove",
    category: "indian",
    emoji: "🕊️",
    description: "Subtle nesting 'croo-croo-oo' calls, echoing warm Indian courtyards",
    waveType: "sine",
    baseFreq: 820,
    freqChange: 80,
    sweepType: "warble",
    duration: 0.75,
    repeatCount: 2,
    interval: 1.1,
    lfoFreq: 4
  },
  {
    id: "coppersmithbarbet",
    name: "Coppersmith Barbet",
    category: "indian",
    emoji: "🔨",
    description: "High-precision rhythmic hollow metallic tolling, like a coppersmith striking metal",
    waveType: "triangle",
    baseFreq: 950,
    freqChange: 0,
    sweepType: "clicks",
    duration: 0.15,
    repeatCount: 12,
    interval: 0.4
  },
  {
    id: "koolparrak",
    name: "Eco-Parrot",
    category: "tropical",
    emoji: "🌴",
    description: "High-energy futuristic laser double sweeps from deep tropical valleys",
    waveType: "sine",
    baseFreq: 2800,
    freqChange: 1500,
    sweepType: "cascade",
    duration: 0.3,
    repeatCount: 4,
    interval: 0.42
  },
  {
    id: "toucancall",
    name: "Emerald Toucanet",
    category: "tropical",
    emoji: "🥑",
    description: "Bubbly rapid gurgled whistle bursts across misty rainforest valleys",
    waveType: "triangle",
    baseFreq: 1100,
    freqChange: 450,
    sweepType: "gurgle",
    duration: 0.32,
    repeatCount: 4,
    interval: 0.45
  },
  {
    id: "superbbird",
    name: "Superb Bird-of-Paradise",
    category: "tropical",
    emoji: "🌌",
    description: "Futuristic digital alarm-like whistling scales with vibrato",
    waveType: "sawtooth",
    baseFreq: 4200,
    freqChange: -1800,
    sweepType: "vibrato",
    duration: 0.25,
    repeatCount: 6,
    interval: 0.32,
    lfoFreq: 24
  },
  {
    id: "ospreywhistle",
    name: "High Osprey Whistle",
    category: "notable",
    emoji: "🦅",
    description: "Crystalline alert alarm whistles cascading downward over ocean peaks",
    waveType: "sine",
    baseFreq: 3400,
    freqChange: -800,
    sweepType: "cascade",
    duration: 0.5,
    repeatCount: 3,
    interval: 0.65
  },
  {
    id: "sandpipers",
    name: "Beach Sandpipers",
    category: "notable",
    emoji: "🏖️",
    description: "Charming rapid-fire shorebird whistles that blend perfectly with continuous ocean waves",
    waveType: "sine",
    baseFreq: 3100,
    freqChange: 400,
    sweepType: "triplet",
    duration: 0.18,
    repeatCount: 6,
    interval: 0.25
  },
  // Indian Additions
  {
    id: "brahminystarling",
    name: "Brahminy Starling",
    category: "indian",
    emoji: "🧡",
    description: "A sweet, conversational series of whistles, clicks, and mimicry echoes",
    waveType: "triangle",
    baseFreq: 2600,
    freqChange: -900,
    sweepType: "clicks",
    duration: 0.22,
    repeatCount: 5,
    interval: 0.3,
    lfoFreq: 14
  },
  {
    id: "malabarlark",
    name: "Malabar Lark",
    category: "indian",
    emoji: "🌾",
    description: "Joyous, rapid scales of whistling notes cascading over coastal meadows",
    waveType: "sine",
    baseFreq: 3100,
    freqChange: 600,
    sweepType: "cascade",
    duration: 0.35,
    repeatCount: 4,
    interval: 0.45,
    lfoFreq: 10
  },
  {
    id: "himalayanmonal",
    name: "Himalayan Monal",
    category: "indian",
    emoji: "🦚",
    description: "Loud, clear rising whistles echoing across high-altitude pine ridges",
    waveType: "sine",
    baseFreq: 1600,
    freqChange: 1200,
    sweepType: "up",
    duration: 0.55,
    repeatCount: 2,
    interval: 0.8
  },
  // Dutch Garden Birds (High SEO value for Netherlands market)
  {
    id: "greattit",
    name: "Great Tit",
    dutchName: "Koolmees",
    category: "songbirds",
    emoji: "🐦",
    description: "Bright two-note 'tea-cher, tea-cher' metallic whistles ringing through gardens",
    waveType: "sine",
    baseFreq: 3400,
    freqChange: -600,
    sweepType: "double",
    duration: 0.2,
    repeatCount: 4,
    interval: 0.35
  },
  {
    id: "houssesparrow",
    name: "House Sparrow",
    dutchName: "Huismus",
    category: "songbirds",
    emoji: "🏘️",
    description: "Lively cheerful chirping and chattering calls from urban rooftops and hedges",
    waveType: "triangle",
    baseFreq: 2800,
    freqChange: 400,
    sweepType: "clicks",
    duration: 0.1,
    repeatCount: 6,
    interval: 0.15
  },
  {
    id: "bluetit",
    name: "Blue Tit",
    dutchName: "Pimpelmees",
    category: "songbirds",
    emoji: "💙",
    description: "High-pitched thin 'tsee-tsee-tsee' trills followed by buzzing chatter",
    waveType: "sine",
    baseFreq: 4200,
    freqChange: -900,
    sweepType: "trill",
    duration: 0.18,
    repeatCount: 5,
    interval: 0.25,
    lfoFreq: 20
  },
  // Belgian Additions
  {
    id: "blackwoodpecker",
    name: "Black Woodpecker",
    category: "belgian",
    emoji: "🐦",
    description: "A loud, ringing 'klee-yah' call and deep resonant pecking sounds",
    waveType: "sawtooth",
    baseFreq: 1100,
    freqChange: -400,
    sweepType: "clicks",
    duration: 0.4,
    repeatCount: 5,
    interval: 0.5
  },
  {
    id: "crestedtit",
    name: "Crested Tit",
    category: "belgian",
    emoji: "🐤",
    description: "A distinctive, rapid purring trill from conifer pines",
    waveType: "sine",
    baseFreq: 4600,
    freqChange: -800,
    sweepType: "trill",
    duration: 0.12,
    repeatCount: 4,
    interval: 0.22,
    lfoFreq: 16
  },
  {
    id: "firecrest",
    name: "Firecrest",
    category: "belgian",
    emoji: "⚡",
    description: "An ultra-high pitch, accelerating series of sweet piping notes",
    waveType: "sine",
    baseFreq: 6400,
    freqChange: 800,
    sweepType: "cascade",
    duration: 0.08,
    repeatCount: 6,
    interval: 0.15,
    lfoFreq: 28
  },
  // Taiwanese Birds
  {
    id: "taiwan-blue-magpie",
    name: "Taiwan Blue Magpie",
    category: "taiwan",
    emoji: "🦜",
    description: "Raucous 'cackle' and flute-like notes — known as the Long-tailed Mountain Lady of Taiwan",
    waveType: "sine",
    baseFreq: 2000,
    freqChange: -600,
    sweepType: "trill",
    duration: 0.35,
    repeatCount: 4,
    interval: 0.55,
    lfoFreq: 14
  },
  // Australian Birds
  {
    id: "kookaburra",
    name: "Laughing Kookaburra",
    category: "australian",
    emoji: "🇦🇺",
    description: "Iconic echoing 'laughing' call that rings across Australian dawn bushland",
    waveType: "triangle",
    baseFreq: 750,
    freqChange: 350,
    sweepType: "warble",
    duration: 0.6,
    repeatCount: 4,
    interval: 0.7,
    lfoFreq: 5
  },
  {
    id: "ganggang-cockatoo",
    name: "Gang-gang Cockatoo",
    category: "australian",
    emoji: "🧡",
    description: "Distinctive creaky door-like 'scraaark' call with rusty hinge charm",
    waveType: "sawtooth",
    baseFreq: 1200,
    freqChange: -300,
    sweepType: "down",
    duration: 0.5,
    repeatCount: 2,
    interval: 0.9
  },
  {
    id: "whipbird",
    name: "Eastern Whipbird",
    category: "australian",
    emoji: "🌿",
    description: "Famous whip-crack sound followed by delicate high chattering notes",
    waveType: "sine",
    baseFreq: 4200,
    freqChange: -1500,
    sweepType: "cascade",
    duration: 0.15,
    repeatCount: 3,
    interval: 0.5
  },
  {
    id: "willywagtail",
    name: "Willie Wagtail",
    category: "australian",
    emoji: "🖤",
    description: "Sweet energetic scolding chatter with rhythmic lively phrasing",
    waveType: "triangle",
    baseFreq: 3500,
    freqChange: 600,
    sweepType: "triplet",
    duration: 0.18,
    repeatCount: 5,
    interval: 0.25
  },
  {
    id: "piedbutcherbird",
    name: "Pied Butcherbird",
    category: "australian",
    emoji: "🎵",
    description: "Beautiful rich fluting carolling melody echoing across open woodlands and ranges",
    waveType: "sine",
    baseFreq: 1600,
    freqChange: 700,
    sweepType: "bell",
    duration: 0.65,
    repeatCount: 3,
    interval: 0.8,
    lfoFreq: 6
  },
  // Japanese Birds
  {
    id: "uguisu",
    name: "Japanese Bush Warbler",
    category: "japan",
    emoji: "🌸",
    description: "Famous 'ho-ho-kekyo' ascending call signalling spring in Japanese gardens",
    waveType: "sine",
    baseFreq: 2400,
    freqChange: 900,
    sweepType: "trill",
    duration: 0.45,
    repeatCount: 3,
    interval: 0.6,
    lfoFreq: 16
  },
  {
    id: "komadori",
    name: "Japanese Robin",
    category: "japan",
    emoji: "🧡",
    description: "Beautiful fluting song with rich bell-like tones from forest undergrowth",
    waveType: "sine",
    baseFreq: 1900,
    freqChange: 500,
    sweepType: "bell",
    duration: 0.55,
    repeatCount: 3,
    interval: 0.7,
    lfoFreq: 7
  },
  {
    id: "redcrownedcrane",
    name: "Red-crowned Crane",
    category: "japan",
    emoji: "🦩",
    description: "Deep trumpeting bugle calls echoing across Hokkaido wetlands",
    waveType: "triangle",
    baseFreq: 550,
    freqChange: 250,
    sweepType: "up",
    duration: 0.8,
    repeatCount: 2,
    interval: 1.2
  },
  {
    id: "mejiro",
    name: "Japanese White-eye",
    category: "japan",
    emoji: "💚",
    description: "High thin sweet warbling chatter from cherry blossom branches",
    waveType: "sine",
    baseFreq: 4500,
    freqChange: 600,
    sweepType: "warble",
    duration: 0.18,
    repeatCount: 6,
    interval: 0.22,
    lfoFreq: 18
  },
  {
    id: "hototogisu",
    name: "Lesser Cuckoo",
    category: "japan",
    emoji: "🕊️",
    description: "Haunting five-note descending whistle beloved in Japanese poetry",
    waveType: "sine",
    baseFreq: 1800,
    freqChange: -500,
    sweepType: "cascade",
    duration: 0.5,
    repeatCount: 3,
    interval: 0.65
  },
  // Chinese Birds
  {
    id: "hwamei",
    name: "Chinese Hwamei",
    category: "china",
    emoji: "🎭",
    description: "Rich melodious songster with beautiful rolling whistles and mimicry",
    waveType: "sine",
    baseFreq: 2100,
    freqChange: 650,
    sweepType: "vibrato",
    duration: 0.5,
    repeatCount: 4,
    interval: 0.6,
    lfoFreq: 12
  },
  {
    id: "redbilledbluemagpie",
    name: "Red-billed Blue Magpie",
    category: "china",
    emoji: "💙",
    description: "Loud chattering metallic calls, highly social and vocal",
    waveType: "triangle",
    baseFreq: 2800,
    freqChange: -700,
    sweepType: "trill",
    duration: 0.25,
    repeatCount: 5,
    interval: 0.3,
    lfoFreq: 20
  },
  {
    id: "silverpheasant",
    name: "Silver Pheasant",
    category: "china",
    emoji: "🪶",
    description: "Sharp repeated alarm whistles from mountain forests",
    waveType: "sawtooth",
    baseFreq: 1500,
    freqChange: -400,
    sweepType: "down",
    duration: 0.35,
    repeatCount: 3,
    interval: 0.5
  },
  {
    id: "mandarinduck",
    name: "Mandarin Duck",
    category: "china",
    emoji: "🦆",
    description: "Soft high whistling calls, gentle and calming",
    waveType: "sine",
    baseFreq: 2200,
    freqChange: 300,
    sweepType: "bell",
    duration: 0.3,
    repeatCount: 3,
    interval: 0.45
  },
  // Brazilian Birds
  {
    id: "sabia",
    name: "Rufous-bellied Thrush",
    category: "brazil",
    emoji: "🇧🇷",
    description: "Brazil's national bird with a famously beautiful fluting evening song",
    waveType: "sine",
    baseFreq: 1700,
    freqChange: 600,
    sweepType: "vibrato",
    duration: 0.6,
    repeatCount: 3,
    interval: 0.75,
    lfoFreq: 8
  },
  {
    id: "queroquero",
    name: "Southern Lapwing",
    category: "brazil",
    emoji: "🌾",
    description: "Loud piercing 'quero-quero' call across Brazilian grasslands",
    waveType: "sawtooth",
    baseFreq: 3200,
    freqChange: -500,
    sweepType: "warble",
    duration: 0.3,
    repeatCount: 4,
    interval: 0.4
  },
  {
    id: "bemtevi",
    name: "Great Kiskadee",
    category: "brazil",
    emoji: "💛",
    description: "Bold three-note 'bem-te-vi' whistle sung throughout tropical Americas",
    waveType: "triangle",
    baseFreq: 1400,
    freqChange: 600,
    sweepType: "triplet",
    duration: 0.35,
    repeatCount: 3,
    interval: 0.5
  },
  {
    id: "bluemacaw",
    name: "Blue-and-yellow Macaw",
    category: "brazil",
    emoji: "🦜",
    description: "Raucous screeching calls echoing through Amazon rainforest canopy",
    waveType: "square",
    baseFreq: 2800,
    freqChange: 800,
    sweepType: "trill",
    duration: 0.4,
    repeatCount: 3,
    interval: 0.55
  },
  {
    id: "screamingpiha",
    name: "Screaming Piha",
    category: "brazil",
    emoji: "🌳",
    description: "Loud explosive descending whistle, one of the Amazon's most iconic sounds",
    waveType: "sine",
    baseFreq: 1800,
    freqChange: -1200,
    sweepType: "down",
    duration: 0.5,
    repeatCount: 2,
    interval: 0.9
  },
  // African Birds
  {
    id: "africanfisheagle",
    name: "African Fish Eagle",
    category: "africa",
    emoji: "🦅",
    description: "Iconic soaring 'weeah-kyow-kyow' call, the sound of the African wilderness",
    waveType: "sine",
    baseFreq: 650,
    freqChange: 450,
    sweepType: "bell",
    duration: 0.7,
    repeatCount: 3,
    interval: 0.9,
    lfoFreq: 4
  },
  {
    id: "hadeda",
    name: "Hadeda Ibis",
    category: "africa",
    emoji: "📯",
    description: "Loud raucous 'ha-da-da' trumpeting call, dawn chorus of suburban Africa",
    waveType: "sawtooth",
    baseFreq: 900,
    freqChange: 300,
    sweepType: "up",
    duration: 0.5,
    repeatCount: 3,
    interval: 0.6
  },
  {
    id: "caperobinchat",
    name: "Cape Robin-chat",
    category: "africa",
    emoji: "🎶",
    description: "Beautiful melodic warbling song with rich varied phrases from thickets",
    waveType: "sine",
    baseFreq: 2300,
    freqChange: 700,
    sweepType: "warble",
    duration: 0.48,
    repeatCount: 4,
    interval: 0.6,
    lfoFreq: 10
  },
  {
    id: "maskedweaver",
    name: "Southern Masked Weaver",
    category: "africa",
    emoji: "🪺",
    description: "Bubbling chattering song full of rapid whistles and buzzes",
    waveType: "triangle",
    baseFreq: 3800,
    freqChange: 800,
    sweepType: "gurgle",
    duration: 0.15,
    repeatCount: 6,
    interval: 0.2
  },
  {
    id: "woodlandkingfisher",
    name: "Woodland Kingfisher",
    category: "africa",
    emoji: "🔵",
    description: "High-pitched trilling 'tree-tree-tree' call of African savanna woodlands",
    waveType: "sine",
    baseFreq: 3400,
    freqChange: 400,
    sweepType: "trill",
    duration: 0.22,
    repeatCount: 5,
    interval: 0.3,
    lfoFreq: 22
  },
  // Middle Eastern Birds
  {
    id: "arabianbabbler",
    name: "Arabian Babbler",
    category: "middleeast",
    emoji: "🗣️",
    description: "Loud chattering group calls from desert wadis and acacia scrub",
    waveType: "triangle",
    baseFreq: 2600,
    freqChange: -500,
    sweepType: "clicks",
    duration: 0.12,
    repeatCount: 8,
    interval: 0.18
  },
  {
    id: "whitecheekedbulbul",
    name: "White-cheeked Bulbul",
    category: "middleeast",
    emoji: "🍇",
    description: "Cheerful bubbly warbling from gardens and date palms across Arabia",
    waveType: "sine",
    baseFreq: 3000,
    freqChange: 500,
    sweepType: "warble",
    duration: 0.25,
    repeatCount: 5,
    interval: 0.3,
    lfoFreq: 14
  },
  {
    id: "desertlark",
    name: "Desert Lark",
    category: "middleeast",
    emoji: "🏜️",
    description: "Sweet descending whistles drifting across sand dunes and rocky plains",
    waveType: "sine",
    baseFreq: 3600,
    freqChange: -800,
    sweepType: "cascade",
    duration: 0.3,
    repeatCount: 4,
    interval: 0.4
  },
  {
    id: "chukar",
    name: "Chukar Partridge",
    category: "middleeast",
    emoji: "⛰️",
    description: "Rhythmic 'chuk-chuk-chukar' calls echoing across rocky mountain slopes",
    waveType: "triangle",
    baseFreq: 1100,
    freqChange: 350,
    sweepType: "double",
    duration: 0.3,
    repeatCount: 4,
    interval: 0.5
  },
  // Nordic & Arctic Birds
  {
    id: "bluethroat",
    name: "Bluethroat",
    category: "nordic",
    emoji: "💎",
    description: "Beautiful varied song with rich mimicry across Scandinavian tundra",
    waveType: "sine",
    baseFreq: 2900,
    freqChange: 800,
    sweepType: "vibrato",
    duration: 0.4,
    repeatCount: 4,
    interval: 0.5,
    lfoFreq: 15
  },
  {
    id: "willowwarbler",
    name: "Willow Warbler",
    category: "nordic",
    emoji: "🌿",
    description: "Descending silvery trill that heralds spring across Nordic forests",
    waveType: "sine",
    baseFreq: 3800,
    freqChange: -900,
    sweepType: "cascade",
    duration: 0.35,
    repeatCount: 4,
    interval: 0.45
  },
  {
    id: "commonloon",
    name: "Common Loon",
    category: "nordic",
    emoji: "🌊",
    description: "Haunting yodelling wail across northern lakes, iconic wilderness sound",
    waveType: "triangle",
    baseFreq: 500,
    freqChange: 350,
    sweepType: "warble",
    duration: 0.9,
    repeatCount: 2,
    interval: 1.3,
    lfoFreq: 3
  },
  {
    id: "snowbunting",
    name: "Snow Bunting",
    category: "nordic",
    emoji: "❄️",
    description: "Cheerful high twittering calls from Arctic tundra and snowy peaks",
    waveType: "sine",
    baseFreq: 5000,
    freqChange: 600,
    sweepType: "triplet",
    duration: 0.15,
    repeatCount: 6,
    interval: 0.2
  },
  {
    id: "greatgreyowl",
    name: "Great Grey Owl",
    category: "nordic",
    emoji: "🦉",
    description: "Deep resonant hooting pulses through silent boreal forest nights",
    waveType: "triangle",
    baseFreq: 350,
    freqChange: 80,
    sweepType: "bell",
    duration: 0.7,
    repeatCount: 3,
    interval: 1.0,
    lfoFreq: 2
  },
  {
    id: "laplandbunting",
    name: "Lapland Bunting",
    category: "nordic",
    emoji: "🌌",
    description: "Delicate jingling tinkling song across Arctic tundra landscapes",
    waveType: "sine",
    baseFreq: 5200,
    freqChange: -600,
    sweepType: "trill",
    duration: 0.2,
    repeatCount: 5,
    interval: 0.28,
    lfoFreq: 24
  },
  // European National Birds
  {
    id: "gallic-rooster",
    name: "Gallic Rooster",
    category: "europe",
    emoji: "🐓",
    description: "France's iconic crowing cock, a symbol of Gallic pride since Roman times",
    waveType: "sawtooth",
    baseFreq: 800,
    freqChange: 600,
    sweepType: "up",
    duration: 0.6,
    repeatCount: 3,
    interval: 0.8
  },
  {
    id: "italian-sparrow",
    name: "Italian Sparrow",
    category: "europe",
    emoji: "🍝",
    description: "Cheerful chirping calls from Italian piazzas and olive groves",
    waveType: "triangle",
    baseFreq: 3100,
    freqChange: 400,
    sweepType: "clicks",
    duration: 0.12,
    repeatCount: 6,
    interval: 0.18
  },
  {
    id: "imperial-eagle",
    name: "Spanish Imperial Eagle",
    category: "europe",
    emoji: "🦅",
    description: "Powerful yelping 'kyaa-kyaa' calls over Iberian oak savannas",
    waveType: "sine",
    baseFreq: 700,
    freqChange: 300,
    sweepType: "up",
    duration: 0.55,
    repeatCount: 3,
    interval: 0.7
  },
  {
    id: "blacktailedgodwit",
    name: "Black-tailed Godwit",
    category: "europe",
    emoji: "🕊️",
    description: "Soft rhythmic 'wicka-wicka-wicka' calls from Dutch meadows and wetlands",
    waveType: "sine",
    baseFreq: 1700,
    freqChange: -300,
    sweepType: "warble",
    duration: 0.3,
    repeatCount: 4,
    interval: 0.4,
    lfoFreq: 8
  },
  {
    id: "whooperswan",
    name: "Whooper Swan",
    category: "europe",
    emoji: "🦢",
    description: "Loud bugling 'whoop-a whoop-a' trumpet calls across Nordic lakes",
    waveType: "triangle",
    baseFreq: 450,
    freqChange: 250,
    sweepType: "bell",
    duration: 0.8,
    repeatCount: 2,
    interval: 1.1
  },
  {
    id: "muteswan",
    name: "Mute Swan",
    category: "europe",
    emoji: "🦢",
    description: "Gentle hissing and soft snorting sounds from Denmark's graceful waterways",
    waveType: "triangle",
    baseFreq: 300,
    freqChange: 100,
    sweepType: "down",
    duration: 0.6,
    repeatCount: 2,
    interval: 0.9
  },
  {
    id: "whitetailedeagle",
    name: "White-tailed Eagle",
    category: "europe",
    emoji: "🦅",
    description: "Deep barking 'kra-kra-kra' calls echoing across Polish and Czech forests",
    waveType: "sawtooth",
    baseFreq: 600,
    freqChange: 200,
    sweepType: "bell",
    duration: 0.5,
    repeatCount: 3,
    interval: 0.65
  },
  {
    id: "gyrfalcon",
    name: "Gyrfalcon",
    category: "europe",
    emoji: "❄️",
    description: "Harsh rapid 'kak-kak-kak' alarm calls from Iceland's Arctic cliffs",
    waveType: "sawtooth",
    baseFreq: 2200,
    freqChange: 500,
    sweepType: "clicks",
    duration: 0.15,
    repeatCount: 6,
    interval: 0.2
  },
  {
    id: "dipper",
    name: "White-throated Dipper",
    category: "europe",
    emoji: "🏔️",
    description: "Loud bubbling warbling song above rushing Norwegian mountain streams",
    waveType: "sine",
    baseFreq: 3000,
    freqChange: 700,
    sweepType: "gurgle",
    duration: 0.35,
    repeatCount: 4,
    interval: 0.45,
    lfoFreq: 12
  },
  {
    id: "goldcrest",
    name: "Goldcrest",
    category: "europe",
    emoji: "👑",
    description: "Ultra-high thin lisping 'see-see-see' from Luxembourg's ancient forests",
    waveType: "sine",
    baseFreq: 6000,
    freqChange: 500,
    sweepType: "trill",
    duration: 0.12,
    repeatCount: 5,
    interval: 0.18,
    lfoFreq: 26
  },
  {
    id: "bluerockthrush",
    name: "Blue Rock Thrush",
    category: "europe",
    emoji: "💙",
    description: "Rich fluting whistles echoing across Malta's rocky Mediterranean coasts",
    waveType: "sine",
    baseFreq: 2000,
    freqChange: 600,
    sweepType: "warble",
    duration: 0.5,
    repeatCount: 3,
    interval: 0.65,
    lfoFreq: 7
  },
  {
    id: "northernlapwing",
    name: "Northern Lapwing",
    category: "europe",
    emoji: "🌾",
    description: "Haunting 'peewit' call over Irish green fields and wetlands",
    waveType: "triangle",
    baseFreq: 2600,
    freqChange: -600,
    sweepType: "bell",
    duration: 0.35,
    repeatCount: 3,
    interval: 0.5
  },
  {
    id: "greatbustard",
    name: "Great Bustard",
    category: "europe",
    emoji: "🏆",
    description: "Deep resonant booming display call across Hungarian plains",
    waveType: "triangle",
    baseFreq: 250,
    freqChange: 150,
    sweepType: "bell",
    duration: 1.0,
    repeatCount: 2,
    interval: 1.5
  },
  {
    id: "littleowl",
    name: "Little Owl",
    category: "europe",
    emoji: "🦉",
    description: "Melancholic 'kiew-kiew' whistling calls at Greek twilight",
    waveType: "sine",
    baseFreq: 1100,
    freqChange: -200,
    sweepType: "double",
    duration: 0.4,
    repeatCount: 3,
    interval: 0.6
  },
  {
    id: "hozegrouse",
    name: "Caucasian Grouse",
    category: "europe",
    emoji: "⛰️",
    description: "Low bubbling lekking display calls from Azerbaijan's mountain meadows",
    waveType: "triangle",
    baseFreq: 600,
    freqChange: 200,
    sweepType: "gurgle",
    duration: 0.45,
    repeatCount: 4,
    interval: 0.55
  },
  // North & Central American National Birds
  {
    id: "american-flamingo",
    name: "American Flamingo",
    category: "northamerica",
    emoji: "🦩",
    description: "Loud goose-like honking calls from Bahamian coral islands and lagoons",
    waveType: "triangle",
    baseFreq: 800,
    freqChange: 400,
    sweepType: "bell",
    duration: 0.5,
    repeatCount: 3,
    interval: 0.7
  },
  {
    id: "brownpelican",
    name: "Brown Pelican",
    category: "northamerica",
    emoji: "🦉",
    description: "Deep grunting croaks from Barbados' coastal cliffs and piers",
    waveType: "triangle",
    baseFreq: 400,
    freqChange: 150,
    sweepType: "down",
    duration: 0.4,
    repeatCount: 3,
    interval: 0.6
  },
  {
    id: "keelbilledtoucan",
    name: "Keel-billed Toucan",
    category: "northamerica",
    emoji: "🌈",
    description: "Frog-like croaking 'rrr-rrr' calls echoing through Belizean rainforest canopy",
    waveType: "triangle",
    baseFreq: 700,
    freqChange: 200,
    sweepType: "gurgle",
    duration: 0.4,
    repeatCount: 4,
    interval: 0.5
  },
  {
    id: "claycoloredthrush",
    name: "Clay-coloured Thrush",
    category: "northamerica",
    emoji: "🎶",
    description: "Costa Rica's national bird with a powerful fluting dawn song",
    waveType: "sine",
    baseFreq: 1900,
    freqChange: 500,
    sweepType: "warble",
    duration: 0.55,
    repeatCount: 3,
    interval: 0.7,
    lfoFreq: 7
  },
  {
    id: "cubantrogon",
    name: "Cuban Trogon",
    category: "northamerica",
    emoji: "🇨🇺",
    description: "Soft 'tocororo' calls with rising inflection from Cuban forests",
    waveType: "sine",
    baseFreq: 1500,
    freqChange: 350,
    sweepType: "double",
    duration: 0.35,
    repeatCount: 3,
    interval: 0.5
  },
  {
    id: "imperial-amazon",
    name: "Imperial Amazon",
    category: "northamerica",
    emoji: "🦜",
    description: "Harsh squawking calls of Dominica's critically endangered Sisserou Parrot",
    waveType: "square",
    baseFreq: 2000,
    freqChange: 500,
    sweepType: "trill",
    duration: 0.35,
    repeatCount: 4,
    interval: 0.45
  },
  {
    id: "palmchat",
    name: "Palmchat",
    category: "northamerica",
    emoji: "🌴",
    description: "Chattering squeaky calls from Dominican Republic's palm groves",
    waveType: "triangle",
    baseFreq: 3200,
    freqChange: 400,
    sweepType: "clicks",
    duration: 0.12,
    repeatCount: 6,
    interval: 0.18
  },
  {
    id: "motmot",
    name: "Turquoise-browed Motmot",
    category: "northamerica",
    emoji: "💎",
    description: "Distinctive low 'hut-hut-hut' hooting calls of El Salvador's Torogoz",
    waveType: "triangle",
    baseFreq: 900,
    freqChange: 150,
    sweepType: "double",
    duration: 0.35,
    repeatCount: 3,
    interval: 0.55
  },
  {
    id: "resplendentquetzal",
    name: "Resplendent Quetzal",
    category: "northamerica",
    emoji: "🪶",
    description: "Gentle 'kow-kow' whistling from Guatemala's cloud forest canopies",
    waveType: "sine",
    baseFreq: 1600,
    freqChange: 250,
    sweepType: "bell",
    duration: 0.4,
    repeatCount: 3,
    interval: 0.6
  },
  {
    id: "streamertail",
    name: "Red-billed Streamertail",
    category: "northamerica",
    emoji: "💚",
    description: "Rapid buzzing 'tick-tick-tick' calls of Jamaica's Doctor Bird",
    waveType: "sawtooth",
    baseFreq: 4500,
    freqChange: 300,
    sweepType: "clicks",
    duration: 0.08,
    repeatCount: 8,
    interval: 0.12
  },
  {
    id: "baldeagle",
    name: "Bald Eagle",
    category: "northamerica",
    emoji: "🇺🇸",
    description: "High thin whistling 'kyaa-kyaa' cries soaring over American wilderness",
    waveType: "sine",
    baseFreq: 900,
    freqChange: 400,
    sweepType: "warble",
    duration: 0.5,
    repeatCount: 3,
    interval: 0.65,
    lfoFreq: 5
  },
  {
    id: "harpyeagle",
    name: "Harpy Eagle",
    category: "northamerica",
    emoji: "🦅",
    description: "Powerful wailing cries from Panama's lowland rainforest canopy",
    waveType: "sine",
    baseFreq: 550,
    freqChange: 300,
    sweepType: "up",
    duration: 0.6,
    repeatCount: 3,
    interval: 0.8
  },
  {
    id: "scarletmacaw",
    name: "Scarlet Macaw",
    category: "northamerica",
    emoji: "❤️",
    description: "Loud harsh squawking screeches across Honduran and Surinamese rainforests",
    waveType: "square",
    baseFreq: 2500,
    freqChange: 800,
    sweepType: "vibrato",
    duration: 0.4,
    repeatCount: 3,
    interval: 0.55,
    lfoFreq: 16
  },
  {
    id: "spindalis",
    name: "Puerto Rican Spindalis",
    category: "northamerica",
    emoji: "🎵",
    description: "High thin warbling song from Puerto Rico's mountain forests",
    waveType: "sine",
    baseFreq: 4200,
    freqChange: 500,
    sweepType: "trill",
    duration: 0.2,
    repeatCount: 4,
    interval: 0.28,
    lfoFreq: 20
  },
  {
    id: "stlucia-amazon",
    name: "St. Lucia Amazon",
    category: "northamerica",
    emoji: "🦜",
    description: "Raucous squawking calls of St. Lucia's endangered Jacquot parrot",
    waveType: "sawtooth",
    baseFreq: 2300,
    freqChange: 600,
    sweepType: "trill",
    duration: 0.3,
    repeatCount: 4,
    interval: 0.4
  },
  {
    id: "scarletibis",
    name: "Scarlet Ibis",
    category: "northamerica",
    emoji: "🔴",
    description: "Low grunting 'grr-grr' calls from Trinidad's Caroni Swamp",
    waveType: "triangle",
    baseFreq: 500,
    freqChange: 150,
    sweepType: "down",
    duration: 0.35,
    repeatCount: 3,
    interval: 0.5
  },
  // South American National Birds
  {
    id: "hornero",
    name: "Rufous Hornero",
    category: "southamerica",
    emoji: "🏠",
    description: "Loud clear 'tru-trriii' whistling duets from Argentina's national bird",
    waveType: "sine",
    baseFreq: 1800,
    freqChange: 600,
    sweepType: "up",
    duration: 0.35,
    repeatCount: 3,
    interval: 0.5
  },
  {
    id: "andeancondor",
    name: "Andean Condor",
    category: "southamerica",
    emoji: "🦅",
    description: "Mostly silent but produces low hissing grunts across Andean peaks",
    waveType: "triangle",
    baseFreq: 300,
    freqChange: 100,
    sweepType: "bell",
    duration: 0.8,
    repeatCount: 2,
    interval: 1.2
  },
  {
    id: "bellbird",
    name: "Bare-throated Bellbird",
    category: "southamerica",
    emoji: "🔔",
    description: "Loud explosive metallic 'DONG' call ringing through Paraguayan forests",
    waveType: "sine",
    baseFreq: 800,
    freqChange: 50,
    sweepType: "bell",
    duration: 0.3,
    repeatCount: 3,
    interval: 0.8
  },
  {
    id: "cockoftherock",
    name: "Andean Cock-of-the-rock",
    category: "southamerica",
    emoji: "🧡",
    description: "Sharp squealing calls from Peru's misty cloud forest leks",
    waveType: "sawtooth",
    baseFreq: 2900,
    freqChange: 700,
    sweepType: "vibrato",
    duration: 0.25,
    repeatCount: 4,
    interval: 0.35,
    lfoFreq: 18
  },
  {
    id: "troupial",
    name: "Venezuelan Troupial",
    category: "southamerica",
    emoji: "🧡",
    description: "Loud fluting whistles with rich melodic phrases from Venezuela's national bird",
    waveType: "sine",
    baseFreq: 2000,
    freqChange: 650,
    sweepType: "warble",
    duration: 0.5,
    repeatCount: 3,
    interval: 0.65,
    lfoFreq: 8
  },
  {
    id: "tocotoucan",
    name: "Toco Toucan",
    category: "southamerica",
    emoji: "🦜",
    description: "Deep croaking frog-like 'rrr-rrr' calls from Brazilian and Guyanan rainforests",
    waveType: "triangle",
    baseFreq: 650,
    freqChange: 150,
    sweepType: "gurgle",
    duration: 0.45,
    repeatCount: 4,
    interval: 0.55
  },
  {
    id: "andeangoose",
    name: "Andean Goose",
    category: "southamerica",
    emoji: "🪿",
    description: "High nasal whistling calls from high-altitude Andean wetlands",
    waveType: "sine",
    baseFreq: 2500,
    freqChange: -400,
    sweepType: "warble",
    duration: 0.35,
    repeatCount: 3,
    interval: 0.5
  },
  // Africa National Birds (batch 2)
  {
    id: "bluecrane",
    name: "Blue Crane",
    category: "africa",
    emoji: "🪶",
    description: "Soft melodious rattling calls from South Africa's Karoo grasslands",
    waveType: "sine",
    baseFreq: 1400,
    freqChange: 400,
    sweepType: "warble",
    duration: 0.5,
    repeatCount: 3,
    interval: 0.6
  },
  {
    id: "crownedcrane",
    name: "Grey Crowned Crane",
    category: "africa",
    emoji: "👑",
    description: "Loud 'waa-waa' honking calls of Uganda and Rwanda's national bird",
    waveType: "triangle",
    baseFreq: 900,
    freqChange: 300,
    sweepType: "bell",
    duration: 0.45,
    repeatCount: 3,
    interval: 0.55
  },
  {
    id: "lilacroller",
    name: "Lilac-breasted Roller",
    category: "africa",
    emoji: "💜",
    description: "Harsh raucous 'rak-rak-rak' calls across Kenya's savanna skies",
    waveType: "sawtooth",
    baseFreq: 2100,
    freqChange: 500,
    sweepType: "clicks",
    duration: 0.2,
    repeatCount: 5,
    interval: 0.3
  },
  {
    id: "kori-bustard",
    name: "Kori Bustard",
    category: "africa",
    emoji: "🦌",
    description: "Deep resonant booming calls of Botswana's heaviest flying bird",
    waveType: "triangle",
    baseFreq: 350,
    freqChange: 100,
    sweepType: "down",
    duration: 0.6,
    repeatCount: 3,
    interval: 0.9
  },
  {
    id: "redcrestedturaco",
    name: "Red-crested Turaco",
    category: "africa",
    emoji: "🔴",
    description: "Loud echoing 'kow-kow-kow' calls from Angola's forest canopies",
    waveType: "sine",
    baseFreq: 1300,
    freqChange: 250,
    sweepType: "bell",
    duration: 0.4,
    repeatCount: 4,
    interval: 0.5
  },
  {
    id: "congopeafowl",
    name: "Congo Peafowl",
    category: "africa",
    emoji: "🦚",
    description: "Deep duetting 'ro-hoo-aa' calls echoing through DRC's rainforest",
    waveType: "sine",
    baseFreq: 700,
    freqChange: 250,
    sweepType: "double",
    duration: 0.5,
    repeatCount: 3,
    interval: 0.7
  },
  {
    id: "tawnyeagle",
    name: "Tawny Eagle",
    category: "africa",
    emoji: "🦅",
    description: "Sharp barking 'kya-kya-kya' calls soaring above Ghana's woodlands",
    waveType: "sine",
    baseFreq: 850,
    freqChange: 300,
    sweepType: "up",
    duration: 0.45,
    repeatCount: 4,
    interval: 0.5
  },
  {
    id: "blackcrownedcrane",
    name: "Black Crowned Crane",
    category: "africa",
    emoji: "🖤",
    description: "Deep resonant 'kaw-kaw' honking of Nigeria's national bird in Sahel wetlands",
    waveType: "triangle",
    baseFreq: 750,
    freqChange: 200,
    sweepType: "bell",
    duration: 0.5,
    repeatCount: 3,
    interval: 0.6
  },
  {
    id: "purpleturaco",
    name: "Purple-crested Turaco",
    category: "africa",
    emoji: "🟣",
    description: "Loud excited 'kroo-kroo' calls from Eswatini's riverine forests",
    waveType: "sine",
    baseFreq: 1600,
    freqChange: 350,
    sweepType: "warble",
    duration: 0.35,
    repeatCount: 3,
    interval: 0.5
  },
  {
    id: "hamerkop",
    name: "Hamerkop",
    category: "africa",
    emoji: "🪶",
    description: "Loud shrill 'yip-yip-yip' calls of Gambia's wading bird",
    waveType: "triangle",
    baseFreq: 2800,
    freqChange: 600,
    sweepType: "clicks",
    duration: 0.15,
    repeatCount: 6,
    interval: 0.2
  },
  {
    id: "commondodo",
    name: "Dodo",
    category: "africa",
    emoji: "🦤",
    description: "Deep low booming calls — Mauritius' extinct icon",
    waveType: "triangle",
    baseFreq: 300,
    freqChange: 50,
    sweepType: "gurgle",
    duration: 0.6,
    repeatCount: 2,
    interval: 1.0
  },
  {
    id: "seychellesparrot",
    name: "Seychelles Black Parrot",
    category: "africa",
    emoji: "🦜",
    description: "Harsh screeching calls from Praslin's palm forests",
    waveType: "square",
    baseFreq: 2600,
    freqChange: 700,
    sweepType: "trill",
    duration: 0.3,
    repeatCount: 4,
    interval: 0.4
  },
  {
    id: "steppeeagle",
    name: "Steppe Eagle",
    category: "africa",
    emoji: "🦅",
    description: "Harsh cawing calls from Egypt's desert skies",
    waveType: "sawtooth",
    baseFreq: 600,
    freqChange: 200,
    sweepType: "down",
    duration: 0.5,
    repeatCount: 3,
    interval: 0.7
  },
  // Oceania National Birds
  {
    id: "kiwi",
    name: "North Island Brown Kiwi",
    category: "oceania",
    emoji: "🥝",
    description: "High-pitched ascending whistling calls at night in New Zealand forests",
    waveType: "sine",
    baseFreq: 2200,
    freqChange: 500,
    sweepType: "up",
    duration: 0.4,
    repeatCount: 3,
    interval: 0.6
  },
  {
    id: "raggianabop",
    name: "Raggiana Bird-of-Paradise",
    category: "oceania",
    emoji: "🪶",
    description: "Harsh 'waa-waa' squawks with mechanical wing sounds from PNG highlands",
    waveType: "square",
    baseFreq: 3000,
    freqChange: 800,
    sweepType: "vibrato",
    duration: 0.25,
    repeatCount: 4,
    interval: 0.35,
    lfoFreq: 20
  },
  {
    id: "collaredlory",
    name: "Collared Lory",
    category: "oceania",
    emoji: "🌈",
    description: "High-pitched screeching calls from Fiji's tropical islands",
    waveType: "sawtooth",
    baseFreq: 3800,
    freqChange: 600,
    sweepType: "trill",
    duration: 0.2,
    repeatCount: 5,
    interval: 0.25
  },
  {
    id: "emu",
    name: "Emu",
    category: "oceania",
    emoji: "🦃",
    description: "Deep low booming drumming sounds from Australia's outback",
    waveType: "triangle",
    baseFreq: 200,
    freqChange: 80,
    sweepType: "gurgle",
    duration: 0.7,
    repeatCount: 3,
    interval: 1.0
  },
  {
    id: "palaufruitdove",
    name: "Palau Fruit Dove",
    category: "oceania",
    emoji: "🕊️",
    description: "Soft cooing 'oo-oo-oo' calls across Palau's limestone islands",
    waveType: "sine",
    baseFreq: 1200,
    freqChange: 200,
    sweepType: "bell",
    duration: 0.4,
    repeatCount: 4,
    interval: 0.5
  },
  // Asia National Birds
  {
    id: "philippineeagle",
    name: "Philippine Eagle",
    category: "asia",
    emoji: "🇵🇭",
    description: "High piercing whistling calls from Philippine rainforest canopies",
    waveType: "sine",
    baseFreq: 950,
    freqChange: 400,
    sweepType: "warble",
    duration: 0.5,
    repeatCount: 3,
    interval: 0.65
  },
  {
    id: "javaneagle",
    name: "Javan Hawk-Eagle",
    category: "asia",
    emoji: "🇮🇩",
    description: "Sharp 'kee-kee' whistling cries from Indonesia's lowland forests",
    waveType: "sine",
    baseFreq: 1700,
    freqChange: 500,
    sweepType: "double",
    duration: 0.35,
    repeatCount: 3,
    interval: 0.5
  },
  {
    id: "rhinohornbill",
    name: "Rhinoceros Hornbill",
    category: "asia",
    emoji: "🦏",
    description: "Powerful 'rohh-rohh' booming calls from Malaysia's rainforest canopy",
    waveType: "triangle",
    baseFreq: 500,
    freqChange: 150,
    sweepType: "bell",
    duration: 0.4,
    repeatCount: 4,
    interval: 0.6
  },
  {
    id: "srirakanjunglefowl",
    name: "Sri Lankan Junglefowl",
    category: "asia",
    emoji: "🇱🇰",
    description: "Distinctive 'koku-ku-kuuu' crowing from Sri Lankan forests",
    waveType: "sawtooth",
    baseFreq: 1500,
    freqChange: 400,
    sweepType: "warble",
    duration: 0.35,
    repeatCount: 3,
    interval: 0.55
  },
  {
    id: "siamesefireback",
    name: "Siamese Fireback",
    category: "asia",
    emoji: "🇹🇭",
    description: "Soft clucking calls with wing-whirring displays in Thai forests",
    waveType: "triangle",
    baseFreq: 1000,
    freqChange: 200,
    sweepType: "clicks",
    duration: 0.2,
    repeatCount: 5,
    interval: 0.3
  },
  {
    id: "koreanmagpie",
    name: "Korean Magpie",
    category: "asia",
    emoji: "🇰🇷",
    description: "Loud chattering 'chak-chak-chak' calls across Korean woodlands",
    waveType: "triangle",
    baseFreq: 3500,
    freqChange: 500,
    sweepType: "clicks",
    duration: 0.12,
    repeatCount: 7,
    interval: 0.15
  },
  {
    id: "giantibis",
    name: "Giant Ibis",
    category: "asia",
    emoji: "🇰🇭",
    description: "Deep 'aarr-aarr' croaking calls from Cambodia's remote wetlands",
    waveType: "triangle",
    baseFreq: 400,
    freqChange: 100,
    sweepType: "gurgle",
    duration: 0.55,
    repeatCount: 3,
    interval: 0.7
  },
  {
    id: "mongolianfalcon",
    name: "Saker Falcon",
    category: "asia",
    emoji: "🇲🇳",
    description: "Sharp 'kya-kya' cries of Mongolia and UAE's national bird",
    waveType: "sine",
    baseFreq: 1300,
    freqChange: 400,
    sweepType: "up",
    duration: 0.35,
    repeatCount: 4,
    interval: 0.5
  }
];
