export interface BirdPreset {
  id: string;
  name: string;
  dutchName?: string;
  category: string;
  emoji: string;
  description: string;
  waveType: "sine" | "triangle" | "sawtooth" | "square";
  baseFreq: number;
  freqChange: number;
  sweepType: "up" | "down" | "vibrato" | "trill" | "double" | "warble" | "bell" | "triplet" | "clicks" | "gurgle" | "cascade";
  duration: number;
  repeatCount: number;
  interval: number;
  lfoFreq?: number;
}

export const BIRD_CATEGORIES = [
  { id: "lofi", name: "🏆 AI & Lo-Fi Essentials" },
  { id: "songbirds", name: "🎵 Songbirds & Melodic Singers" },
  { id: "mimics", name: "🎭 Mimics & Complex Vocalists" },
  { id: "flute", name: "🎷 Whistling & Flute-Like" },
  { id: "indian", name: "🇮🇳 Indian Birds (Beautiful Songs)" },
  { id: "belgian", name: "🇧🇪 Belgian Ardennes Birds" },
  { id: "taiwan", name: "🇹🇼 Taiwanese Birds" },
  { id: "australian", name: "🇦🇺 Australian Birds" },
  { id: "tropical", name: "🌴 Tropical & Exotic Voices" },
  { id: "notable", name: "🌟 Additional Notable Singers" }
];

export const BIRD_PRESETS: BirdPreset[] = [
  // SECTION 1: AI & Lo-Fi Essentials (Top recommendations for beat crafting)
  {
    id: "malabarwhistlingthrush",
    name: "Malabar Whistling Thrush",
    category: "lofi",
    emoji: "🎶",
    description: "Whistling idle schoolboy tune; blends perfectly with mellow lo-fi chords",
    waveType: "sine",
    baseFreq: 1800,
    freqChange: -400,
    sweepType: "warble",
    duration: 0.65,
    repeatCount: 4,
    interval: 0.75,
    lfoFreq: 6
  },
  {
    id: "shama",
    name: "White-rumped Shama",
    category: "lofi",
    emoji: "🧡",
    description: "Flute-like liquid melodies, rich echoes, outstanding for spatial ambient pads",
    waveType: "sine",
    baseFreq: 2200,
    freqChange: 800,
    sweepType: "vibrato",
    duration: 0.55,
    repeatCount: 3,
    interval: 0.65,
    lfoFreq: 14
  },
  {
    id: "asiankoel",
    name: "Asian Koel",
    category: "lofi",
    emoji: "🖤",
    description: "Rising full-throated 'ko-el... ko-el' call that signals tropical nights",
    waveType: "sine",
    baseFreq: 1100,
    freqChange: 700,
    sweepType: "up",
    duration: 0.45,
    repeatCount: 2,
    interval: 0.8
  },
  {
    id: "nightingale",
    name: "Common Nightingale",
    dutchName: "Nachtegaal",
    category: "lofi",
    emoji: "🌙",
    description: "Famous deep romantic night-time warble with emotional piping tones",
    waveType: "triangle",
    baseFreq: 1950,
    freqChange: 350,
    sweepType: "trill",
    duration: 0.5,
    repeatCount: 4,
    interval: 0.55,
    lfoFreq: 18
  },
  {
    id: "tui",
    name: "Tui",
    category: "lofi",
    emoji: "🇳🇿",
    description: "Exotic bell chimes, mechanical clicks, and deep fluted note drops",
    waveType: "triangle",
    baseFreq: 2500,
    freqChange: -1200,
    sweepType: "bell",
    duration: 0.35,
    repeatCount: 5,
    interval: 0.4,
    lfoFreq: 8
  },
  {
    id: "skylark",
    name: "Common Skylark",
    dutchName: "Veldleeuwerik",
    category: "lofi",
    emoji: "☁️",
    description: "Cascading rapid wall of high-frequency joyous whistles",
    waveType: "sine",
    baseFreq: 3400,
    freqChange: -900,
    sweepType: "cascade",
    duration: 0.4,
    repeatCount: 6,
    interval: 0.45,
    lfoFreq: 22
  },
  {
    id: "woodthrush",
    name: "Wood Thrush",
    dutchName: "Boslijster",
    category: "lofi",
    emoji: "🌲",
    description: "High clear crystalline double-flute sounds resonant across forest floors",
    waveType: "sine",
    baseFreq: 2100,
    freqChange: 500,
    sweepType: "double",
    duration: 0.48,
    repeatCount: 3,
    interval: 0.6
  },
  {
    id: "magpierobin",
    name: "Oriental Magpie-Robin",
    category: "lofi",
    emoji: "🤍",
    description: "Loud, highly-varied whistling scales with rich natural echo response",
    waveType: "sine",
    baseFreq: 2300,
    freqChange: -600,
    sweepType: "triplet",
    duration: 0.38,
    repeatCount: 3,
    interval: 0.5
  },
  {
    id: "canary",
    name: "Warbler Canary",
    category: "lofi",
    emoji: "🟡",
    description: "Fast cheerful golden ripples, classical musical trills & whistles",
    waveType: "triangle",
    baseFreq: 2800,
    freqChange: 400,
    sweepType: "vibrato",
    duration: 0.6,
    repeatCount: 3,
    interval: 0.7,
    lfoFreq: 12
  },
  {
    id: "bulbul",
    name: "Red-whiskered Bulbul",
    category: "lofi",
    emoji: "🍓",
    description: "Happy bouncy bubbly 'pettigrew' whistling sound, highly positive vibe",
    waveType: "sine",
    baseFreq: 1650,
    freqChange: 350,
    sweepType: "gurgle",
    duration: 0.28,
    repeatCount: 4,
    interval: 0.35
  },

  // SECTION 2: Songbirds & Melodic Singers
  {
    id: "robin",
    name: "European Robin",
    dutchName: "Roodborst",
    category: "songbirds",
    emoji: "🐤",
    description: "A series of swift, sweet piping trilled notes rising and falling",
    waveType: "sine",
    baseFreq: 2900,
    freqChange: 600,
    sweepType: "trill",
    duration: 0.3,
    repeatCount: 3,
    interval: 0.4,
    lfoFreq: 15
  },
  {
    id: "blackbird",
    name: "Common Blackbird",
    dutchName: "Merel",
    category: "songbirds",
    emoji: "🐦",
    description: "Deep, rich fluid whistling scales with beautiful melancholy hooks",
    waveType: "sine",
    baseFreq: 1400,
    freqChange: 350,
    sweepType: "warble",
    duration: 0.7,
    repeatCount: 3,
    interval: 0.9,
    lfoFreq: 5
  },
  {
    id: "songthrush",
    name: "Song Thrush",
    dutchName: "Zanglijster",
    category: "songbirds",
    emoji: "🎤",
    description: "Repeats clear brief patterns inside tree tops three to four times",
    waveType: "sine",
    baseFreq: 2500,
    freqChange: -800,
    sweepType: "double",
    duration: 0.35,
    repeatCount: 4,
    interval: 0.45
  },
  {
    id: "hermitthrush",
    name: "Hermit Thrush",
    category: "songbirds",
    emoji: "🍃",
    description: "Pure ethereal fluted pipes cascading downwards at high frequencies",
    waveType: "sine",
    baseFreq: 3100,
    freqChange: -1200,
    sweepType: "cascade",
    duration: 0.5,
    repeatCount: 3,
    interval: 0.65
  },
  {
    id: "housefinch",
    name: "House Finch",
    category: "songbirds",
    emoji: "🏡",
    description: "Bright energetic singing tweets that climb up with a final upward buzz",
    waveType: "sine",
    baseFreq: 2700,
    freqChange: 800,
    sweepType: "up",
    duration: 0.24,
    repeatCount: 5,
    interval: 0.3
  },
  {
    id: "purplefinch",
    name: "Purple Finch",
    category: "songbirds",
    emoji: "💜",
    description: "Lyrical bubbling stream of rapid sweet whistling syllables",
    waveType: "triangle",
    baseFreq: 2600,
    freqChange: 450,
    sweepType: "gurgle",
    duration: 0.32,
    repeatCount: 4,
    interval: 0.4
  },
  {
    id: "goldfinch",
    name: "American Goldfinch",
    category: "songbirds",
    emoji: "🌻",
    description: "Light bouncy cheerful sliding tweets, sounds like 'po-ta-to-chip!'",
    waveType: "sine",
    baseFreq: 3100,
    freqChange: 600,
    sweepType: "triplet",
    duration: 0.2,
    repeatCount: 4,
    interval: 0.32
  },
  {
    id: "yellowhammer",
    name: "Yellowhammer",
    dutchName: "Geelgors",
    category: "songbirds",
    emoji: "🥖",
    description: "Famous rapid monotone notes ending on a long down-slurred whistling sigh",
    waveType: "sine",
    baseFreq: 2400,
    freqChange: -600,
    sweepType: "down",
    duration: 0.8,
    repeatCount: 2,
    interval: 1.0
  },
  {
    id: "indigobunting",
    name: "Indigo Bunting",
    category: "songbirds",
    emoji: "💙",
    description: "High-spirited rapid doublets; notes are always grouped in pairs",
    waveType: "sine",
    baseFreq: 3300,
    freqChange: -700,
    sweepType: "double",
    duration: 0.25,
    repeatCount: 6,
    interval: 0.35
  },
  {
    id: "eastmeadowlark",
    name: "Eastern Meadowlark",
    category: "songbirds",
    emoji: "🌾",
    description: "Slow lazy sliding sweet whistling bells typical of morning grasslands",
    waveType: "sine",
    baseFreq: 2100,
    freqChange: -500,
    sweepType: "bell",
    duration: 0.65,
    repeatCount: 3,
    interval: 0.85
  },
  {
    id: "westmeadowlark",
    name: "Western Meadowlark",
    category: "songbirds",
    emoji: "🤠",
    description: "Rich, bubbly, flute-like gurgled notes cascading down dynamically",
    waveType: "triangle",
    baseFreq: 1750,
    freqChange: -750,
    sweepType: "gurgle",
    duration: 0.55,
    repeatCount: 3,
    interval: 0.72
  },

  // SECTION 3: Mimics & Complex Vocalists
  {
    id: "mockingbird",
    name: "Northern Mockingbird",
    category: "mimics",
    emoji: "🎭",
    description: "Cleverly repeats other bird calls in sequences of threes",
    waveType: "sine",
    baseFreq: 2200,
    freqChange: 300,
    sweepType: "triplet",
    duration: 0.25,
    repeatCount: 6,
    interval: 0.35
  },
  {
    id: "lyrebird",
    name: "Superb Lyrebird",
    category: "mimics",
    emoji: "🪕",
    description: "Amazing metal clicks, chainsaw buzzes, camera clicks & laser bleeps",
    waveType: "sawtooth",
    baseFreq: 4000,
    freqChange: -3500,
    sweepType: "clicks",
    duration: 0.18,
    repeatCount: 8,
    interval: 0.25
  },
  {
    id: "magpie",
    name: "Australian Magpie",
    category: "mimics",
    emoji: "🇦🇺",
    description: "Incredibly deep rich pipe-organ liquid carol whistles",
    waveType: "sine",
    baseFreq: 950,
    freqChange: 650,
    sweepType: "warble",
    duration: 0.7,
    repeatCount: 3,
    interval: 0.8,
    lfoFreq: 4
  },
  {
    id: "starling",
    name: "European Starling",
    dutchName: "Spreeuw",
    category: "mimics",
    emoji: "🔋",
    description: "Cosmic series of whistles, chattering clocks, and high digital beeps",
    waveType: "square",
    baseFreq: 3800,
    freqChange: -2000,
    sweepType: "clicks",
    duration: 0.1,
    repeatCount: 10,
    interval: 0.15
  },
  {
    id: "catbird",
    name: "Gray Catbird",
    category: "mimics",
    emoji: "🐱",
    description: "Nasal cat-like 'meow' call blended with high melodic whistle trills",
    waveType: "triangle",
    baseFreq: 1800,
    freqChange: -400,
    sweepType: "down",
    duration: 0.5,
    repeatCount: 3,
    interval: 0.6
  },

  // SECTION 4: Whistling & Flute-Like Voices
  {
    id: "indiancuckoo",
    name: "Indian Cuckoo",
    category: "flute",
    emoji: "⏱️",
    description: "Four-note rhythmic musical whistle resembling 'one-more-bottle'",
    waveType: "sine",
    baseFreq: 1250,
    freqChange: 150,
    sweepType: "double",
    duration: 0.35,
    repeatCount: 4,
    interval: 0.45
  },
  {
    id: "commoncuckoo",
    name: "Common Cuckoo",
    dutchName: "Koekoek",
    category: "flute",
    emoji: "🕰️",
    description: "Classic pristine double-tone 'coo-coo' scale drop in spring woods",
    waveType: "sine",
    baseFreq: 1050,
    freqChange: -230,
    sweepType: "double",
    duration: 0.4,
    repeatCount: 2,
    interval: 0.7
  },
  {
    id: "whistlingthrush",
    name: "Whistling Thrush",
    category: "flute",
    emoji: "🌬️",
    description: "Extremely loud high flute-like whistles sliding down deeply",
    waveType: "sine",
    baseFreq: 2600,
    freqChange: -1100,
    sweepType: "down",
    duration: 0.75,
    repeatCount: 3,
    interval: 0.9
  },
  {
    id: "goldenoriole",
    name: "Golden Oriole",
    dutchName: "Wielewaal",
    category: "flute",
    emoji: "💛",
    description: "Exquisite warm liquid flute 'weela-wee-ooo' whistle loop",
    waveType: "sine",
    baseFreq: 1150,
    freqChange: 450,
    sweepType: "bell",
    duration: 0.58,
    repeatCount: 3,
    interval: 0.75
  },
  {
    id: "blacknapedoriole",
    name: "Black-naped Oriole",
    category: "flute",
    emoji: "🐥",
    description: "Rich clear whistling bird melody resounding in bamboo groves",
    waveType: "sine",
    baseFreq: 1350,
    freqChange: -300,
    sweepType: "triplet",
    duration: 0.4,
    repeatCount: 3,
    interval: 0.6
  },
  {
    id: "baltimoreoriole",
    name: "Baltimore Oriole",
    category: "flute",
    emoji: "🧡",
    description: "Short series of bright rich piping double notes with spacious pausing",
    waveType: "sine",
    baseFreq: 1900,
    freqChange: 550,
    sweepType: "double",
    duration: 0.5,
    repeatCount: 3,
    interval: 0.7
  },

  // SECTION 5: Indian Birds with Beautiful Songs
  {
    id: "indianrobin",
    name: "Indian Robin",
    category: "indian",
    emoji: "🇮🇳",
    description: "Quick slide-whistles ending on high-precision sweet chirps",
    waveType: "sine",
    baseFreq: 2350,
    freqChange: 650,
    sweepType: "up",
    duration: 0.28,
    repeatCount: 4,
    interval: 0.42
  },
  {
    id: "flycatcher",
    name: "Indian Paradise Flycatcher",
    category: "indian",
    emoji: "🤍",
    description: "Short quick flute whistle with sudden high-pitched whip snaps",
    waveType: "triangle",
    baseFreq: 2400,
    freqChange: 1200,
    sweepType: "clicks",
    duration: 0.15,
    repeatCount: 5,
    interval: 0.25
  },
  {
    id: "redventedbulbul",
    name: "Red-vented Bulbul",
    category: "indian",
    emoji: "🍒",
    description: "Short bubbly gurgled whistles, highly rhythmic and quick",
    waveType: "sine",
    baseFreq: 1550,
    freqChange: 250,
    sweepType: "gurgle",
    duration: 0.25,
    repeatCount: 4,
    interval: 0.32
  },
  {
    id: "junglebabbler",
    name: "Jungle Babbler",
    category: "indian",
    emoji: "🗣️",
    description: "Famous noisy chattering squeaks delivered synchronously in groups of seven",
    waveType: "triangle",
    baseFreq: 1250,
    freqChange: -450,
    sweepType: "clicks",
    duration: 0.12,
    repeatCount: 6,
    interval: 0.18
  },
  {
    id: "commoniora",
    name: "Common Iora",
    category: "indian",
    emoji: "🍋",
    description: "Very long high sustained piping whistle dropping off instantly at the end",
    waveType: "sine",
    baseFreq: 2600,
    freqChange: -1400,
    sweepType: "down",
    duration: 1.1,
    repeatCount: 1,
    interval: 1.5
  },
  {
    id: "indianpitta",
    name: "Indian Pitta",
    category: "indian",
    emoji: "🌈",
    description: "Loud, clear double-whistle 'wheet-tew' rising then dropping rapidly",
    waveType: "sine",
    baseFreq: 1850,
    freqChange: -600,
    sweepType: "double",
    duration: 0.45,
    repeatCount: 2,
    interval: 0.6
  },
  {
    id: "purplesunbird",
    name: "Purple Sunbird",
    category: "indian",
    emoji: "🍇",
    description: "Rapid energetic buzzing metallic click hums that shift frequency",
    waveType: "sawtooth",
    baseFreq: 4500,
    freqChange: -1800,
    sweepType: "vibrato",
    duration: 0.12,
    repeatCount: 8,
    interval: 0.18,
    lfoFreq: 25
  },

  // SECTION 6: Tropical & Exotic Voices
  {
    id: "bellbird",
    name: "New Zealand Bellbird",
    category: "tropical",
    emoji: "🔔",
    description: "Pristine ringing metallic bell chime tones, extremely high fidelity",
    waveType: "sine",
    baseFreq: 3200,
    freqChange: -800,
    sweepType: "bell",
    duration: 0.45,
    repeatCount: 4,
    interval: 0.5
  },
  {
    id: "kokako",
    name: "Kokako",
    category: "tropical",
    emoji: "🌫️",
    description: "Hauntingly slow, deep organ-pipe notes that drift through coastal mist",
    waveType: "sine",
    baseFreq: 850,
    freqChange: 150,
    sweepType: "warble",
    duration: 0.95,
    repeatCount: 2,
    interval: 1.2,
    lfoFreq: 3
  },
  {
    id: "paradistanager",
    name: "Paradise Tanager",
    category: "tropical",
    emoji: "🦜",
    description: "High insect-like rapid electric buzzing sweeps across Amazon canopy",
    waveType: "square",
    baseFreq: 4800,
    freqChange: -1500,
    sweepType: "vibrato",
    duration: 0.22,
    repeatCount: 5,
    interval: 0.28,
    lfoFreq: 30
  },
  {
    id: "scarlettanager",
    name: "Scarlet Tanager",
    category: "tropical",
    emoji: "🎒",
    description: "Raspy, hurried whistling slide; sounds like a robin with a draft cold",
    waveType: "triangle",
    baseFreq: 1850,
    freqChange: 350,
    sweepType: "gurgle",
    duration: 0.4,
    repeatCount: 3,
    interval: 0.55
  },
  {
    id: "cedarwaxwing",
    name: "Cedar Waxwing",
    category: "tropical",
    emoji: "🍒",
    description: "Extremely high thin sibilant lisping whistles that sound like electricity",
    waveType: "sine",
    baseFreq: 6200,
    freqChange: -800,
    sweepType: "trill",
    duration: 0.25,
    repeatCount: 4,
    interval: 0.3,
    lfoFreq: 28
  },
  {
    id: "bohemianwaxwing",
    name: "Bohemian Waxwing",
    category: "tropical",
    emoji: "🍁",
    description: "Ringing high pitch trills similar to small glass bells shaking",
    waveType: "sine",
    baseFreq: 5800,
    freqChange: 300,
    sweepType: "vibrato",
    duration: 0.35,
    repeatCount: 3,
    interval: 0.45,
    lfoFreq: 24
  },
  {
    id: "bluebird",
    name: "Eastern Bluebird",
    category: "tropical",
    emoji: "💙",
    description: "Charming soft warbled slide whistle whistles, rich in peacefulness",
    waveType: "sine",
    baseFreq: 2450,
    freqChange: -450,
    sweepType: "warble",
    duration: 0.48,
    repeatCount: 3,
    interval: 0.65,
    lfoFreq: 5
  },
  {
    id: "rosebreastedgrosbeak",
    name: "Rose-breasted Grosbeak",
    category: "tropical",
    emoji: "🌹",
    description: "Joyful sweet lyrical sliding peaks with deep warmth",
    waveType: "sine",
    baseFreq: 2150,
    freqChange: 750,
    sweepType: "up",
    duration: 0.5,
    repeatCount: 3,
    interval: 0.62
  },
  {
    id: "cardinal",
    name: "Northern Cardinal",
    category: "tropical",
    emoji: "❤️",
    description: "High slurred laser-like 'cheer-cheer-cheer' sweeps that echo widely",
    waveType: "sine",
    baseFreq: 1800,
    freqChange: 1500,
    sweepType: "up",
    duration: 0.45,
    repeatCount: 4,
    interval: 0.6
  },

  // SECTION 7: Additional Notable Singers
  {
    id: "blackheadedgrosbeak",
    name: "Black-headed Grosbeak",
    category: "notable",
    emoji: "🕶️",
    description: "Fast-moving warm gurgling rolling melody; highly complex",
    waveType: "sine",
    baseFreq: 2200,
    freqChange: 400,
    sweepType: "gurgle",
    duration: 0.42,
    repeatCount: 4,
    interval: 0.52
  },
  {
    id: "warblingvireo",
    name: "Warbling Vireo",
    category: "notable",
    emoji: "🎼",
    description: "Very long continuous cheerful wavy phrase that loops elegantly",
    waveType: "sine",
    baseFreq: 2850,
    freqChange: -650,
    sweepType: "warble",
    duration: 0.85,
    repeatCount: 2,
    interval: 1.1,
    lfoFreq: 8
  },
  {
    id: "marshwarbler",
    name: "Marsh Warbler",
    dutchName: "Waterrietzanger",
    category: "notable",
    emoji: "🌾",
    description: "Blisteringly rapid continuous imitations mixed with sweet sliding notes",
    waveType: "triangle",
    baseFreq: 3500,
    freqChange: -1200,
    sweepType: "cascade",
    duration: 0.22,
    repeatCount: 8,
    interval: 0.28,
    lfoFreq: 15
  },
  {
    id: "sedgewarbler",
    name: "Sedge Warbler",
    dutchName: "Rietzanger",
    category: "notable",
    emoji: "🦆",
    description: "Gritty chatter-buzzes blended with sudden bright sliding whistles",
    waveType: "sawtooth",
    baseFreq: 3200,
    freqChange: 1000,
    sweepType: "clicks",
    duration: 0.18,
    repeatCount: 6,
    interval: 0.24
  },
  {
    id: "woodlark",
    name: "Woodlark",
    dutchName: "Boomleeuwerik",
    category: "notable",
    emoji: "🪵",
    description: "Melancholic, beautifully cascading descending'lu-lu-lu' notes",
    waveType: "sine",
    baseFreq: 2100,
    freqChange: -850,
    sweepType: "cascade",
    duration: 0.58,
    repeatCount: 4,
    interval: 0.7
  },
  {
    id: "nightingalethrush",
    name: "Nightingale Thrush",
    category: "notable",
    emoji: "🍂",
    description: "Very delicate fluted warbling notes with quiet woodland space",
    waveType: "sine",
    baseFreq: 2400,
    freqChange: -450,
    sweepType: "triplet",
    duration: 0.4,
    repeatCount: 3,
    interval: 0.65
  },
  {
    id: "robinchat",
    name: "Red-capped Robin-Chat",
    category: "notable",
    emoji: "🧢",
    description: "Exceptional beautiful fluid whistles and perfect mimic sequences",
    waveType: "sine",
    baseFreq: 1950,
    freqChange: 650,
    sweepType: "vibrato",
    duration: 0.52,
    repeatCount: 3,
    interval: 0.68,
    lfoFreq: 12
  },
  {
    id: "laughingthrush",
    name: "Laughingthrush",
    category: "notable",
    emoji: "😆",
    description: "Humorous, loud laughing human-like chatters delivered at high volume",
    waveType: "triangle",
    baseFreq: 1400,
    freqChange: 900,
    sweepType: "gurgle",
    duration: 0.35,
    repeatCount: 4,
    interval: 0.48
  },
  {
    id: "silvereye",
    name: "Silvereye",
    category: "notable",
    emoji: "👓",
    description: "Sweet delicate quiet sliding chirps from low tree hedges",
    waveType: "sine",
    baseFreq: 3700,
    freqChange: -500,
    sweepType: "down",
    duration: 0.18,
    repeatCount: 5,
    interval: 0.25
  },
  {
    id: "bushlark",
    name: "Bush Lark",
    category: "notable",
    emoji: "🌱",
    description: "Brief charming whistles mixed with dry rapid grasswing buzzing",
    waveType: "sawtooth",
    baseFreq: 2900,
    freqChange: -600,
    sweepType: "clicks",
    duration: 0.15,
    repeatCount: 6,
    interval: 0.22
  },
  {
    id: "mourningdove",
    name: "Mourning Dove",
    category: "flute",
    emoji: "🕊️",
    description: "Gentle, soothing coo-OOO-oo-oo calls; creates rich nostalgic morning memories",
    waveType: "sine",
    baseFreq: 900,
    freqChange: 150,
    sweepType: "warble",
    duration: 0.8,
    repeatCount: 3,
    interval: 1.1,
    lfoFreq: 3
  },
  {
    id: "forestowl",
    name: "Forest Owl",
    category: "notable",
    emoji: "🦉",
    description: "Deep hooting pulses echo resonant across remote late-night woodland trails",
    waveType: "triangle",
    baseFreq: 450,
    freqChange: 50,
    sweepType: "bell",
    duration: 0.65,
    repeatCount: 2,
    interval: 0.9,
    lfoFreq: 2
  },
  {
    id: "lilacroller",
    name: "Lilac-breasted Roller",
    category: "tropical",
    emoji: "🌸",
    description: "Energetic vibrant rolling whistles with warm high-harmonic savanna tones",
    waveType: "sawtooth",
    baseFreq: 3100,
    freqChange: -400,
    sweepType: "vibrato",
    duration: 0.35,
    repeatCount: 4,
    interval: 0.5,
    lfoFreq: 18
  },
  {
    id: "woodwarbler",
    name: "Wood Warbler",
    category: "songbirds",
    emoji: "🐤",
    description: "Fascinating high-pitch metallic shivering song that accelerates like a spinning coin",
    waveType: "sine",
    baseFreq: 3300,
    freqChange: -900,
    sweepType: "cascade",
    duration: 0.45,
    repeatCount: 7,
    interval: 0.38,
    lfoFreq: 25
  },
  {
    id: "magpiemelody",
    name: "Australian Magpie Melody",
    category: "lofi",
    emoji: "🖤",
    description: "Flute-like wavy carol chimes with rich ambient depth",
    waveType: "sine",
    baseFreq: 1100,
    freqChange: 550,
    sweepType: "warble",
    duration: 0.6,
    repeatCount: 3,
    interval: 0.8,
    lfoFreq: 6
  },
  {
    id: "nightjar",
    name: "Common Nightjar",
    category: "lofi",
    emoji: "🦉",
    description: "A rapid mechanical woodblock clicking sound; spectacular lofi background texture",
    waveType: "triangle",
    baseFreq: 850,
    freqChange: -150,
    sweepType: "clicks",
    duration: 0.08,
    repeatCount: 16,
    interval: 0.1
  },
  {
    id: "mockingthrush",
    name: "Chuchu Thrush",
    category: "songbirds",
    emoji: "🐦",
    description: "Sudden bright double cascade whistles that repeat with perfect rhythm",
    waveType: "sine",
    baseFreq: 2200,
    freqChange: -800,
    sweepType: "double",
    duration: 0.35,
    repeatCount: 4,
    interval: 0.5
  },
  {
    id: "paintedbunting",
    name: "Painted Bunting",
    category: "songbirds",
    emoji: "🎨",
    description: "A cluster of sweet melodic upward sweeps, extremely rich in harmonics",
    waveType: "sine",
    baseFreq: 3100,
    freqChange: 700,
    sweepType: "up",
    duration: 0.28,
    repeatCount: 5,
    interval: 0.35
  },
  {
    id: "winterwren",
    name: "Winter Wren",
    category: "songbirds",
    emoji: "🪵",
    description: "High-precision rapid cascading trills that shimmer like morning dew",
    waveType: "sine",
    baseFreq: 3800,
    freqChange: -1400,
    sweepType: "vibrato",
    duration: 0.2,
    repeatCount: 8,
    interval: 0.24,
    lfoFreq: 22
  },
  {
    id: "mistlethrush",
    name: "Mistle Thrush",
    dutchName: "Grote Lijster",
    category: "songbirds",
    emoji: "🍂",
    description: "A slow melancholic sliding flute scale; highly peaceful at dusk",
    waveType: "sine",
    baseFreq: 1800,
    freqChange: -300,
    sweepType: "down",
    duration: 0.7,
    repeatCount: 3,
    interval: 0.9
  },
  {
    id: "parakeet",
    name: "Rose-ringed Parakeet",
    category: "mimics",
    emoji: "🦜",
    description: "Vibrant sassy chatter with beautiful high-frequency vibrato elements",
    waveType: "sawtooth",
    baseFreq: 2900,
    freqChange: 400,
    sweepType: "vibrato",
    duration: 0.15,
    repeatCount: 5,
    interval: 0.22,
    lfoFreq: 16
  },
  {
    id: "catbirdblue",
    name: "Blue Gray Catbird",
    category: "mimics",
    emoji: "🐈",
    description: "Playful mimicking slide whistle with a funny nasal tone",
    waveType: "triangle",
    baseFreq: 1600,
    freqChange: -350,
    sweepType: "down",
    duration: 0.45,
    repeatCount: 4,
    interval: 0.55
  },
  {
    id: "spottedbowerbird",
    name: "Spotted Bowerbird",
    category: "mimics",
    emoji: "🏡",
    description: "An incredible range of rapid digital clicking notes and high fluted drops",
    waveType: "square",
    baseFreq: 3400,
    freqChange: -1800,
    sweepType: "clicks",
    duration: 0.12,
    repeatCount: 8,
    interval: 0.18
  },
  {
    id: "hoopoe",
    name: "Eurasian Hoopoe",
    dutchName: "Hop",
    category: "flute",
    emoji: "👑",
    description: "Muffled rhythmic 'oop-oop-oop' double sounds; highly comforting",
    waveType: "sine",
    baseFreq: 680,
    freqChange: 50,
    sweepType: "double",
    duration: 0.35,
    repeatCount: 3,
    interval: 0.65
  },
  {
    id: "taigaflycatcher",
    name: "Taiga Flycatcher",
    category: "flute",
    emoji: "🌲",
    description: "Short double-pulsed high frequency whistle, pristine and clean",
    waveType: "sine",
    baseFreq: 3200,
    freqChange: 300,
    sweepType: "double",
    duration: 0.22,
    repeatCount: 4,
    interval: 0.3
  },
  {
    id: "plaintivecuckoo",
    name: "Plaintive Cuckoo",
    category: "flute",
    emoji: "🌧️",
    description: "Sorrowful high-pitched whistles drooping downwards in rain forests",
    waveType: "sine",
    baseFreq: 2600,
    freqChange: -800,
    sweepType: "down",
    duration: 0.8,
    repeatCount: 3,
    interval: 1.0
  },
  {
    id: "piedcuckoo",
    name: "Pied Crested Cuckoo",
    category: "indian",
    emoji: "🌩️",
    description: "High-frequency rain herald whistles; beautiful double tone",
    waveType: "sine",
    baseFreq: 2400,
    freqChange: 600,
    sweepType: "double",
    duration: 0.4,
    repeatCount: 3,
    interval: 0.58
  },
  {
    id: "tickellsflycatcher",
    name: "Tickell's Blue Flycatcher",
    category: "indian",
    emoji: "💙",
    description: "Very fast metallic warble scales; signs of clean riverbanks",
    waveType: "sine",
    baseFreq: 3300,
    freqChange: -600,
    sweepType: "trill",
    duration: 0.28,
    repeatCount: 5,
    interval: 0.35,
    lfoFreq: 18
  },
  {
    id: "spotteddove",
    name: "Spotted Dove",
    category: "indian",
    emoji: "🕊️",
    description: "Subtle nesting 'croo-croo-oo' calls, echoing warm Indian courtyards",
    waveType: "sine",
    baseFreq: 820,
    freqChange: 80,
    sweepType: "warble",
    duration: 0.75,
    repeatCount: 2,
    interval: 1.1,
    lfoFreq: 4
  },
  {
    id: "coppersmithbarbet",
    name: "Coppersmith Barbet",
    category: "indian",
    emoji: "🔨",
    description: "High-precision rhythmic hollow metallic tolling, like a coppersmith striking metal",
    waveType: "triangle",
    baseFreq: 950,
    freqChange: 0,
    sweepType: "clicks",
    duration: 0.15,
    repeatCount: 12,
    interval: 0.4
  },
  {
    id: "koolparrak",
    name: "Eco-Parrot",
    category: "tropical",
    emoji: "🌴",
    description: "High-energy futuristic laser double sweeps from deep tropical valleys",
    waveType: "sine",
    baseFreq: 2800,
    freqChange: 1500,
    sweepType: "cascade",
    duration: 0.3,
    repeatCount: 4,
    interval: 0.42
  },
  {
    id: "toucancall",
    name: "Emerald Toucanet",
    category: "tropical",
    emoji: "🥑",
    description: "Bubbly rapid gurgled whistle bursts across misty rainforest valleys",
    waveType: "triangle",
    baseFreq: 1100,
    freqChange: 450,
    sweepType: "gurgle",
    duration: 0.32,
    repeatCount: 4,
    interval: 0.45
  },
  {
    id: "superbbird",
    name: "Superb Bird-of-Paradise",
    category: "tropical",
    emoji: "🌌",
    description: "Futuristic digital alarm-like whistling scales with vibrato",
    waveType: "sawtooth",
    baseFreq: 4200,
    freqChange: -1800,
    sweepType: "vibrato",
    duration: 0.25,
    repeatCount: 6,
    interval: 0.32,
    lfoFreq: 24
  },
  {
    id: "ospreywhistle",
    name: "High Osprey Whistle",
    category: "notable",
    emoji: "🦅",
    description: "Crystalline alert alarm whistles cascading downward over ocean peaks",
    waveType: "sine",
    baseFreq: 3400,
    freqChange: -800,
    sweepType: "cascade",
    duration: 0.5,
    repeatCount: 3,
    interval: 0.65
  },
  {
    id: "sandpipers",
    name: "Beach Sandpipers",
    category: "notable",
    emoji: "🏖️",
    description: "Charming rapid-fire shorebird whistles that blend perfectly with continuous ocean waves",
    waveType: "sine",
    baseFreq: 3100,
    freqChange: 400,
    sweepType: "triplet",
    duration: 0.18,
    repeatCount: 6,
    interval: 0.25
  },
  // Indian Additions
  {
    id: "brahminystarling",
    name: "Brahminy Starling",
    category: "indian",
    emoji: "🧡",
    description: "A sweet, conversational series of whistles, clicks, and mimicry echoes",
    waveType: "triangle",
    baseFreq: 2600,
    freqChange: -900,
    sweepType: "clicks",
    duration: 0.22,
    repeatCount: 5,
    interval: 0.3,
    lfoFreq: 14
  },
  {
    id: "malabarlark",
    name: "Malabar Lark",
    category: "indian",
    emoji: "🌾",
    description: "Joyous, rapid scales of whistling notes cascading over coastal meadows",
    waveType: "sine",
    baseFreq: 3100,
    freqChange: 600,
    sweepType: "cascade",
    duration: 0.35,
    repeatCount: 4,
    interval: 0.45,
    lfoFreq: 10
  },
  {
    id: "himalayanmonal",
    name: "Himalayan Monal",
    category: "indian",
    emoji: "🦚",
    description: "Loud, clear rising whistles echoing across high-altitude pine ridges",
    waveType: "sine",
    baseFreq: 1600,
    freqChange: 1200,
    sweepType: "up",
    duration: 0.55,
    repeatCount: 2,
    interval: 0.8
  },
  // Dutch Garden Birds (High SEO value for Netherlands market)
  {
    id: "greattit",
    name: "Great Tit",
    dutchName: "Koolmees",
    category: "songbirds",
    emoji: "🐦",
    description: "Bright two-note 'tea-cher, tea-cher' metallic whistles ringing through gardens",
    waveType: "sine",
    baseFreq: 3400,
    freqChange: -600,
    sweepType: "double",
    duration: 0.2,
    repeatCount: 4,
    interval: 0.35
  },
  {
    id: "houssesparrow",
    name: "House Sparrow",
    dutchName: "Huismus",
    category: "songbirds",
    emoji: "🏘️",
    description: "Lively cheerful chirping and chattering calls from urban rooftops and hedges",
    waveType: "triangle",
    baseFreq: 2800,
    freqChange: 400,
    sweepType: "clicks",
    duration: 0.1,
    repeatCount: 6,
    interval: 0.15
  },
  {
    id: "bluetit",
    name: "Blue Tit",
    dutchName: "Pimpelmees",
    category: "songbirds",
    emoji: "💙",
    description: "High-pitched thin 'tsee-tsee-tsee' trills followed by buzzing chatter",
    waveType: "sine",
    baseFreq: 4200,
    freqChange: -900,
    sweepType: "trill",
    duration: 0.18,
    repeatCount: 5,
    interval: 0.25,
    lfoFreq: 20
  },
  // Belgian Additions
  {
    id: "blackwoodpecker",
    name: "Black Woodpecker",
    category: "belgian",
    emoji: "🐦",
    description: "A loud, ringing 'klee-yah' call and deep resonant pecking sounds",
    waveType: "sawtooth",
    baseFreq: 1100,
    freqChange: -400,
    sweepType: "clicks",
    duration: 0.4,
    repeatCount: 5,
    interval: 0.5
  },
  {
    id: "crestedtit",
    name: "Crested Tit",
    category: "belgian",
    emoji: "🐤",
    description: "A distinctive, rapid purring trill from conifer pines",
    waveType: "sine",
    baseFreq: 4600,
    freqChange: -800,
    sweepType: "trill",
    duration: 0.12,
    repeatCount: 4,
    interval: 0.22,
    lfoFreq: 16
  },
  {
    id: "firecrest",
    name: "Firecrest",
    category: "belgian",
    emoji: "⚡",
    description: "An ultra-high pitch, accelerating series of sweet piping notes",
    waveType: "sine",
    baseFreq: 6400,
    freqChange: 800,
    sweepType: "cascade",
    duration: 0.08,
    repeatCount: 6,
    interval: 0.15,
    lfoFreq: 28
  },
  // Taiwanese Birds
  {
    id: "taiwan-blue-magpie",
    name: "Taiwan Blue Magpie",
    category: "taiwan",
    emoji: "🦜",
    description: "Raucous 'cackle' and flute-like notes — known as the Long-tailed Mountain Lady of Taiwan",
    waveType: "sine",
    baseFreq: 2000,
    freqChange: -600,
    sweepType: "trill",
    duration: 0.35,
    repeatCount: 4,
    interval: 0.55,
    lfoFreq: 14
  },
  // Australian Birds
  {
    id: "kookaburra",
    name: "Laughing Kookaburra",
    category: "australian",
    emoji: "🇦🇺",
    description: "Iconic echoing 'laughing' call that rings across Australian dawn bushland",
    waveType: "triangle",
    baseFreq: 750,
    freqChange: 350,
    sweepType: "warble",
    duration: 0.6,
    repeatCount: 4,
    interval: 0.7,
    lfoFreq: 5
  },
  {
    id: "ganggang-cockatoo",
    name: "Gang-gang Cockatoo",
    category: "australian",
    emoji: "🧡",
    description: "Distinctive creaky door-like 'scraaark' call with rusty hinge charm",
    waveType: "sawtooth",
    baseFreq: 1200,
    freqChange: -300,
    sweepType: "down",
    duration: 0.5,
    repeatCount: 2,
    interval: 0.9
  },
  {
    id: "whipbird",
    name: "Eastern Whipbird",
    category: "australian",
    emoji: "🌿",
    description: "Famous whip-crack sound followed by delicate high chattering notes",
    waveType: "sine",
    baseFreq: 4200,
    freqChange: -1500,
    sweepType: "cascade",
    duration: 0.15,
    repeatCount: 3,
    interval: 0.5
  },
  {
    id: "willywagtail",
    name: "Willie Wagtail",
    category: "australian",
    emoji: "🖤",
    description: "Sweet energetic scolding chatter with rhythmic lively phrasing",
    waveType: "triangle",
    baseFreq: 3500,
    freqChange: 600,
    sweepType: "triplet",
    duration: 0.18,
    repeatCount: 5,
    interval: 0.25
  },
  {
    id: "piedbutcherbird",
    name: "Pied Butcherbird",
    category: "australian",
    emoji: "🎵",
    description: "Beautiful rich fluting carolling melody echoing across open woodlands and ranges",
    waveType: "sine",
    baseFreq: 1600,
    freqChange: 700,
    sweepType: "bell",
    duration: 0.65,
    repeatCount: 3,
    interval: 0.8,
    lfoFreq: 6
  }
];
